bug de nombre largo de evento y estilo reportes
pisgrupo9/ash_web pull request #106
Opened 2016-10-15 22:19 UTC by joacolej

2016-10-15 22:29 UTC, bernabe9 requested changes

2016-10-15 22:29 UTC, bernabe9 commented on src/styles/animal-list.scss
> +  overflow: hidden;
La solucion NO seria ocultar lo q no entra de la palabra, sino quebrar la palabra con un guion por ejemplo.
Esto se logra con la propiedad `word-break` http://www.w3schools.com/cssref/css3_pr_word-break.asp

2016-10-15 22:29 UTC, bernabe9 commented on src/styles/animal-list.scss
> +  flex: 3;
Usa flex definiendo las 3 propiedades, asi no dejas nada librado al azar, esto es generalmente lo que rompe safari.
https://css-tricks.com/snippets/css/a-guide-to-flexbox/

Seguramente: `flex: 3 1 auto;` te funcione, pero probalo

2016-10-15 22:29 UTC, bernabe9 commented on src/styles/report-page.scss
> +    margin: 10px 20px 10px 20px;
seria lo mismo `margin: 10px 20px;`

2016-10-15 22:31 UTC, joacolej commented on src/styles/animal-list.scss
> +  overflow: hidden;
no estoy de acuerdo, para mi hay que hacer como hicimos con los nombres en la lista

2016-10-15 22:31 UTC, joacolej commented on src/styles/animal-list.scss
> +  overflow: hidden;
de animales

2016-10-15 22:32 UTC, joacolej commented on src/styles/report-page.scss
> +    margin: 10px 20px 10px 20px;
no la tenia esa

2016-10-16 01:34 UTC, bernabe9 approved these changes

2016-10-16 01:34 UTC, merged