Test para el formulario de un usuario
pisgrupo9/ash_web pull request #107
Opened 2016-10-15 22:47 UTC by Isa14

2016-10-16 01:23 UTC, bernabe9 requested changes

2016-10-16 01:23 UTC, bernabe9 commented on package.json
> +    "test": "mocha tools/testSetup.js \"src/**/*.spec.js\" --reporter spec",
porque cambiaste esto?

2016-10-16 01:28 UTC, bernabe9 requested changes

2016-10-16 01:28 UTC, bernabe9 commented on src/components/users/UserForm.spec.js
> +import expect from 'expect';
deberia ser `import {expect} from 'chai';`

2016-10-16 01:31 UTC, Isa14 commented on package.json
> +    "test": "mocha tools/testSetup.js \"src/**/*.spec.js\" --reporter spec",
Es para que me diga que tests pasan y cuales no. Si no me dice casi informacion. Pero lo puedo cambiar si queres, y cuando yo pruebe lo cambio para mi y ta

2016-10-17 19:15 UTC, bernabe9 commented
Hiciste todos test estaticos, estaria bueno que uses `sinon` para hacer funciones stub y probar cosas mas dinamicas. 
Aca tenes un ejemplo de un test de un formulario: https://github.com/coryhouse/react-slingshot/blob/master/src/components/FuelSavingsForm.spec.js

Ya que vamos a hacer solo test de algunas cosas estaria bueno que queden medios completos :)

2016-10-20 18:10 UTC, joacolej commented on package.json
> +    "test": "mocha tools/testSetup.js \"src/**/*.spec.js\" --reporter spec",
re quemado el berna

2016-11-03 01:04 UTC, bernabe9 requested changes

2016-11-03 01:04 UTC, bernabe9 commented on src/actions/userActions.spec.js
> +//import nock from 'nock';
elimina esta linea comentada

2016-11-03 01:04 UTC, bernabe9 commented on src/actions/userActions.spec.js
> +
elimina esta linea

2016-11-03 01:04 UTC, bernabe9 commented on src/actions/userActions.spec.js
> +
elimina esta linea

2016-11-03 01:04 UTC, bernabe9 commented on src/components/users/UserForm.spec.js
> +    user: user,
solo `user`

2016-11-03 01:04 UTC, bernabe9 commented on src/components/users/UserForm.spec.js
> +    onSave: onSave,
solo `onSave`

2016-11-03 01:04 UTC, bernabe9 commented on src/reducers/userFormReducer.spec.js
> +describe('Course Reducer', () => {
`Course Reducer` esto me suena a copy and paste

2016-11-03 01:04 UTC, bernabe9 commented on src/reducers/userFormReducer.spec.js
> +    const action = { type: types.SEND_USER_FORM_ERROR, errors: errors };
mal identado

2016-11-03 01:04 UTC, bernabe9 commented on src/reducers/userFormReducer.spec.js
> +    const action = { type: types.SEND_USER_UPDATE_PASS_ERROR, response: response };
mal identado

2016-11-03 01:04 UTC, bernabe9 commented on src/reducers/userFormReducer.spec.js
> +    const action = { type: types.SEND_USER_UPDATE_PASS_ERROR, response: response };
mal identado

2016-11-03 01:04 UTC, bernabe9 commented on src/store/store.spec.js
> +  //Deberia devolverlo, pero el usuario sigue siendo vacio
este test no esta funcional, agregale un comentario que se va a corregir en el futuro

2016-11-03 01:04 UTC, bernabe9 commented on tools/testSetup.js
> +const jsdom = require('jsdom').jsdom;
deja este js como estaba

2016-11-15 22:21 UTC, Isa14 commented on tools/testSetup.js
> +const jsdom = require('jsdom').jsdom;
Lo uso para cuando hago las llamadas mount()

2016-11-17 02:31 UTC, bernabe9 requested changes

2016-11-17 02:31 UTC, bernabe9 commented on package.json
> +    "test": "mocha tools/testSetup.js \"src/**/*.spec.js\" --reporter spec",
deja todo este archivo como estaba, menos lo de `jsdom`

2016-11-17 02:31 UTC, bernabe9 commented on src/actions/userActions.spec.js
> +      const expectedAction = { type: types.SEND_USER_FORM_ERROR, errors: errors };
solo `errors`

2016-11-17 02:31 UTC, bernabe9 commented on src/actions/userActions.spec.js
> +        const user = {
mal identado

2016-11-17 02:31 UTC, bernabe9 commented on src/actions/userActions.spec.js
> +      it('Devuelve la acción sendUserFormSuccess al ejecutar sendUserForm', () => {
deja linea vacia arriba

2016-11-17 02:31 UTC, bernabe9 commented on src/actions/userActions.spec.js
> +        nock(consts.API_STAGING_URL)
repetis el mismo `nock` que arriba

2016-11-17 02:31 UTC, bernabe9 commented on src/actions/userActions.spec.js
> +        expect(store.getState().user).to.not.equal({});
Si decis q no cambia el store porque este test te pasa si comparas con `not equal`.
Ademas estas agarrando mal del store, porque tenes que comparar con `userForm` no con `user`

2016-11-17 02:31 UTC, bernabe9 commented on src/actions/userActions.spec.js
> +      const history = ["http://example/solicitud-registro"];
single qoutes

2016-11-17 02:31 UTC, bernabe9 commented on src/actions/userActions.spec.js
> +      const history = ["http://example/solicitud-registro"];
ya usaste un history igual, sacalo mas para afuera

2016-11-17 02:31 UTC, bernabe9 commented on src/actions/userActions.spec.js
> +      it('Devuelve la acción sendUserFormError al ejecutar sendUserForm', () => {
deja una linea vacia arriba

2016-11-17 02:31 UTC, bernabe9 commented on src/actions/userActions.spec.js
> +          expect(store.getActions()).to.equal(expectedAction[0]["errors"]);
usa dot notation para acceder a las propiedades de los objetos

2016-11-17 02:31 UTC, bernabe9 commented on src/actions/userActions.spec.js
> +        nock(consts.API_STAGING_URL)
nock repetido

2016-11-17 02:31 UTC, bernabe9 commented on src/containers/CreateUserPage.js
> +export class CreateUserPage extends Component {
deja esta linea como estaba

2016-11-17 02:31 UTC, bernabe9 commented on src/containers/CreateUserPage.spec.js
> +	it('Errores locales con usuario vacío', () => {
mal identado

2016-11-17 02:31 UTC, bernabe9 commented on src/containers/CreateUserPage.spec.js
> +    const props = {
props repetidas

2016-11-17 02:31 UTC, bernabe9 commented on src/containers/CreateUserPage.spec.js
> +       name: 'Test One',
mal identado

2016-11-17 02:31 UTC, bernabe9 commented on src/containers/CreateUserPage.spec.js
> +    const props = {
repetido

2016-11-17 02:31 UTC, bernabe9 commented on src/containers/CreateUserPage.spec.js
> +    const props = {
repetido

2016-11-17 02:31 UTC, bernabe9 commented on src/containers/CreateUserPage.spec.js
> +    const nuevoEstado = {
en vez de hacer un `nuevoEstado` cada vez que queres probar un campo diferente, hace un estado generico al principio y despues solo modifica los campos que vas a probar, te vas a ahorrar bastantes lineas de codigo

2016-11-17 02:31 UTC, bernabe9 commented on src/reducers/userFormReducer.spec.js
> +    const action = { type: types.SEND_USER_FORM_ERROR, errors: errors };
solo `errors`

2016-11-17 02:31 UTC, bernabe9 commented on src/reducers/userFormReducer.spec.js
> +    const expected = Object.assign(errors);
No necesitas hacer `Object.assign`

2016-11-17 02:31 UTC, bernabe9 commented on src/reducers/userFormReducer.spec.js
> +    const action = { type: types.SEND_USER_UPDATE_PASS_ERROR, response: response };
solo `response`

2016-11-17 02:31 UTC, bernabe9 commented on src/reducers/userFormReducer.spec.js
> +    const action = { type: types.SEND_USER_UPDATE_PASS_ERROR, response: response };
solo `response`

2016-11-18 22:16 UTC, Isa14 commented on src/containers/CreateUserPage.js
> +export class CreateUserPage extends Component {
Al final probando con esto no me anduvo 'mount(<Provider store={store}><LoginPage {...props} /></Provider>);' El wrapper me queda con state = null

2016-11-18 22:37 UTC, bernabe9 commented on src/containers/CreateUserPage.js
> +export class CreateUserPage extends Component {
No hay chance de que modifiques esta linea, corre riesgo la aplicacion, porque despues cuando se exporta el componente te lo puede devolver sin conectarlo al store.

2016-11-19 02:03 UTC, bernabe9 approved these changes

2016-11-19 02:03 UTC, merged