Show lista adoptantes
pisgrupo9/ash_web pull request #110
Opened 2016-10-16 20:12 UTC by davidgivad

Funcionalidad de listar adoptantes
![screenshot from 2016-10-16 17-11-13](https://cloud.githubusercontent.com/assets/21270775/19420529/a990610c-93c3-11e6-8121-218c2afdac7b.png)

2016-10-16 20:56 UTC, bernabe9 requested changes

2016-10-16 20:56 UTC, bernabe9 commented on src/actions/actionTypes.js
> +export const LOAD_MORE_ADOPTERS_SUCCESS = 'LOAD_MORE_ADOPTERS_SUCCESS';
viendo el codigo podes evitar `LOAD_MORE_ADOPTERS_SUCCESS` y `LOAD_MORE_BLACKLSITED_SUCCESS`. Porque repetis abundante codigo. Solo usando `LOAD_ADOPTERS_SUCCESS` y `LOAD_BLACKLISTED_SUCCES` y una accion que limpie `CLEAN_ADOPTERS` es suficiente, mas claro y menos codigo

2016-10-16 20:56 UTC, bernabe9 commented on src/actions/actionTypes.js
> +export const LOAD_MORE_ADOPTERS_SUCCESS = 'LOAD_MORE_ADOPTERS_SUCCESS';
Mas parecido a como se hace en el load events. Vos copiaste lo q se hizo en load animals y lo de `LOAD_MORE_ADOPTERS_SUCCESS` se agrego por una situacion en particular. Cuando desmontas el componente limpias los adopters y listo

2016-10-16 20:56 UTC, bernabe9 commented on src/components/adopters/AdopterList.js
> +      { loadingList ? spinnerList : showBlacklist
mucha logica para encapsuar dentro del html, sacalo para afuera, ademas el shorthand if se usa para cosas chicas, si son cosas con muchas condiciones queda mas claro el if

2016-10-16 20:56 UTC, bernabe9 commented on src/components/adopters/AdopterList.js
> +            <AdopterItem adopter={adopter} key={adopter.id}
una propiedad por linea

2016-10-16 20:56 UTC, bernabe9 commented on src/components/adopters/AdopterList.js
> +        {loading ? spinner : showViewMore ?
no uses el shorthand if con mas de una condiciones queda inentendible para el que lo lee

2016-10-16 20:56 UTC, bernabe9 commented on src/reducers/initialState.js
> +    total_pages: 0,
usa camelCase para las variables

2016-10-16 20:56 UTC, bernabe9 commented on src/reducers/initialState.js
> +    first_page: false
lo mismo aca

2016-10-16 20:56 UTC, bernabe9 commented on src/styles/adopter-list.scss
> +  flex: 5;
flex completo

2016-10-16 20:56 UTC, bernabe9 commented on src/styles/adopter-list.scss
> +  flex: 0;
flex completo

2016-10-16 20:56 UTC, bernabe9 commented on src/styles/adopter-list.scss
> +  flex: 5;
flex completo

2016-10-16 20:56 UTC, bernabe9 commented on src/styles/adopter-list.scss
> +  flex: 0;
flex completo

2016-10-16 21:42 UTC, davidgivad commented on src/components/adopters/AdopterList.js
> +      { loadingList ? spinnerList : showBlacklist
como seria?

2016-10-16 21:46 UTC, bernabe9 commented on src/components/adopters/AdopterList.js
> +      { loadingList ? spinnerList : showBlacklist
hace una o varias funcion `const` afuera q te maneje todo eso

2016-10-16 23:22 UTC, bernabe9 requested changes

2016-10-16 23:22 UTC, bernabe9 commented on src/api/adopterApi.js
> +export default AdopterApi;
esta linea tiene q ir antes del `export const parseAdopter` sino explotan esas funciones

2016-10-16 23:22 UTC, bernabe9 commented on src/components/adopters/AdopterList.js
> +  if (showBlacklist) {
porque necesitas un showBlackList si el backend ya te los esta filtrando? Lo q se renderiza deberia ser lo mismo para cuando es `showBlackList` como cuando no, los elementos te los da el backend

2016-10-16 23:22 UTC, bernabe9 commented on src/styles/adopter-list.scss
> +  flex: 0 0 0;
que raro esto.. no uses 0 en la ultima propiedad

2016-10-16 23:29 UTC, davidgivad commented on src/components/adopters/AdopterList.js
> +  if (showBlacklist) {
porque uso viewMore() que traen animales no filtrados. Sino tendria que hacer una funcion viewMore Blacklist

2016-10-16 23:37 UTC, bernabe9 requested changes
Te esta faltando un clean de la lista de adopters, va a generar bugs sino

2016-10-16 23:37 UTC, bernabe9 commented on src/components/adopters/AdopterList.js
> +  if (showBlacklist) {
No digo que elimines la variable `showBlackList` digo que lo que mostras en este if es lo mismo q en el else.
Podrias hacer:
```
let adopterShowList = adopters.map(adopter => {
  return (
    adopter.blacklisted ?
      <AdopterItem adopter={adopter}
                            key={adopter.id}
                            selectedAdopterId={selectedAdopterId}
                            onClick={onClick}/>
      : ''  
  );
});
```

no hay necesidad de comprobar que `adopter.blacklisted`

2016-10-16 23:37 UTC, bernabe9 commented on src/components/adopters/AdopterListHeader.js
> +  const buttonBlacklist = (<button className="button-list" onClick={onClickBlacklist}>
seria `buttonBlackList`

2016-10-16 23:37 UTC, bernabe9 commented on src/components/adopters/AdopterListWrapper.js
> +      showBlacklist: false,
seria `showBlackList`

2016-10-16 23:46 UTC, bernabe9 commented
Correcciones visuales:
- Cuando entro me muestra dos spinners cargando
- Cuando cambio a blacklist me muestra el spinner con el `Ver Mas`
- Cuando tengo una cantidad menor que la necesaria para hacer `Ver Mas` de todas formas me muestra el `Ver Mas`
- Si salgo y vuelvo a entrar me saltan errores en la consola(seguramente porque no haces clean cuando desmontas el componente)
- La linea de abajo de la mini view que sea gris o un negro como el del diseño

2016-10-17 00:34 UTC, bernabe9 requested changes

2016-10-17 00:34 UTC, bernabe9 commented on src/actions/adopterActions.js
> +export const loadBlacklisted = (col, row) => {
Llama esta accion de otra forma tipo: `loadSearchAdopters` porque lo q estas haciendo es un search. Y pensando a futuro esta accion se puede reutlizar. Ademas pasale un parametro que sea `filter`

2016-10-17 00:34 UTC, bernabe9 commented on src/actions/adopterActions.js
> +export const loadBlacklistedSuccess = (response) => {
lo mismo aca

2016-10-17 00:34 UTC, bernabe9 commented on src/api/adopterApi.js
> +    return api.get(`${consts.API_STAGING_URL}/adopters/search?blacklisted=true&page=${col}&row=${row}`);
lo mismo aca, no hardcodees el `blacklisted=true` , pasalo por parametro como un filtro, asi en el futuro se pueden agregar mas filtros

2016-10-17 05:28 UTC, davidgivad commented on src/components/adopters/AdopterListHeader.js
> +  const buttonBlacklist = (<button className="button-list" onClick={onClickBlacklist}>
blacklist es una palabra

2016-10-17 15:20 UTC, bernabe9 requested changes

2016-10-17 15:20 UTC, bernabe9 commented on src/actions/actionTypes.js
> +export const LOAD_BLACKLISTED_SUCCESS = 'LOAD_BLACKLISTED_SUCCESS';
la idea es q le cambies el nombre a todo.. asi se puede reutilizar. aca seria `LOAD_SEARCH_SUCCESS` por ejemplo

2016-10-17 15:20 UTC, bernabe9 commented on src/actions/adopterActions.js
> +export const loadBlacklistedSuccess = (response, filterParam) => {
lo mismo aca

2016-10-17 15:20 UTC, bernabe9 commented on src/api/adopterApi.js
> +  static getBlacklisted(row, col, filterParam) {
lo mismo aca

2016-10-17 15:20 UTC, bernabe9 commented on src/api/adopterApi.js
> +    return api.get(`${consts.API_STAGING_URL}/adopters/search?blacklisted=${filterParam}&page=${col}&row=${row}`);
en lo posible no harcodees `blacklisted` pensalo como un filtro mas

2016-10-17 15:20 UTC, bernabe9 commented on src/components/adopters/AdopterList.js
> +  if (showBlacklist) {
Bueno entonces estamos frente a un error muy grande.. Si haces click view more y justo los proximos son todos no black listed entonces no va  a pasar nada.
Te sugiero que mires el `view more` de listar animales.
Ademas te sugiero que no uses dos acciones diferentes para traer los animales, podes usar solo `getAdopters()` , y te fijas si hay filtros, si hay filtros entonces llamas al search, como se hace en listar animales

2016-10-17 16:41 UTC, bernabe9 requested changes

2016-10-17 16:41 UTC, bernabe9 commented on src/actions/adopterActions.js
> +  if (!filterParam || filterParam == '') {
porque no pones esto en `loadAdopters`. sino tiene filtros entonces haces dispachas `getAdopters` y si tiene filtro despachas `getSearchAdopters`, de esta manera en el `view more`siempre llamas a a `loadAdopters` y listo

2016-10-17 17:02 UTC, bernabe9 requested changes

2016-10-17 17:02 UTC, bernabe9 commented on src/components/adopters/AdopterListWrapper.js
> +    if (showBlacklist) {
seria lo mismo `this.props.actions.loadAdopters(rows, nextPage, showBlacklist);` que todo este if y else

2016-10-17 17:02 UTC, bernabe9 commented on src/components/adopters/AdopterListWrapper.js
> +  onClickBlacklist() {
esta funcion hace lo mismo q la de abajo. Podrias hacer una sola y ingeniandote un poco evitas reptir codigo y lineas. Podria ser una funcion tipo `onToggleSearch()`

2016-10-17 17:02 UTC, bernabe9 commented on src/reducers/adoptersReducer.js
> +    case types.LOAD_SEARCH_SUCCESS: {
esta accion hace exactamente lo mismo que `LOAD_ADPOTERS_SUCCESS` . Eliminala

2016-10-17 17:04 UTC, bernabe9 requested changes

2016-10-17 17:04 UTC, bernabe9 commented on src/actions/adopterActions.js
> +    filterParam: filterParam,
le pasas esto a la accion pero despues no lo usas

2016-10-17 20:17 UTC, bernabe9 approved these changes

2016-10-17 20:17 UTC, merged