Editar Adoptante
pisgrupo9/ash_web pull request #120
Opened 2016-10-20 02:04 UTC by felparodi

Se crea el modificar animal con el mismo diseño que el crear

No esta el checbox de la black list

2016-10-20 17:29 UTC, joacolej commented on src/components/common/DatePickerInput.js
> +  onChange: func
por que no es requerido? pregunto nomas

2016-10-20 17:29 UTC, joacolej commented on src/constants/apiMessage.js
> +export const SUCCESS_UPDATE_ADOPTER = 'El adoptante se a modificado con exito';
"ha" en vez de "a"

2016-10-20 17:29 UTC, joacolej commented on src/containers/EditAdopterModal.js
> +        if (myAdoter[name] !== adopter[name]) {
myAdopter, falta una p, igual no es muy important

2016-10-20 17:33 UTC, felparodi commented on src/components/common/DatePickerInput.js
> +  onChange: func
Fue para poder usar el disabled sin riesgo de que hiciera algo, y al ser requerido tira warning

2016-10-20 17:39 UTC, joacolej commented on src/components/common/DatePickerInput.js
> +  onChange: func
(y)

2016-10-20 20:35 UTC, bernabe9 commented
Arquitectura para mantener las cosas como se vienen haciendo:
1- `src/components/adopter/AdopterFormEdit.js` deberia moverse a `src/components/adopters/AdopterFormEdit.js`
2- `src/components/adopter/AdopterInfo.js` deberia moverse a
`src/components/adopters/AdopterInfo.js`

2016-10-20 20:57 UTC, bernabe9 requested changes

2016-10-20 20:57 UTC, bernabe9 commented on src/containers/AdopterPerfilPage.js
> +      adopterId: null,
Si el `adopterId` va a ser un string tiene mas sentido inicializarlo con el string vacio `''`.
Al menos de que exista otra razon

2016-10-20 20:57 UTC, bernabe9 commented on src/containers/EditAdopterModal.js
> +        home_address: '',
usa camel case

2016-10-20 20:57 UTC, bernabe9 commented on src/containers/EditAdopterModal.js
> +        house_description: ''
lo mismo

2016-10-20 20:57 UTC, bernabe9 commented on src/containers/EditAdopterModal.js
> +        home_address: '',
lo mismo

2016-10-20 20:57 UTC, bernabe9 commented on src/containers/EditAdopterModal.js
> +        house_description: ''
lo mismo

2016-10-20 20:57 UTC, bernabe9 commented on src/containers/EditAdopterModal.js
> +        home_address: true,
lo mismo

2016-10-20 20:57 UTC, bernabe9 commented on src/containers/EditAdopterModal.js
> +      for (let name in myAdoter) {
El componente no se deberia encargar de parsear el adopter, tenes que mandar el adopter como esta y que el `adopterApi` tenga una funcion que parsee

2016-10-20 20:57 UTC, bernabe9 commented
No tiene spinner cuando submiteas

2016-10-20 20:58 UTC, bernabe9 requested changes

2016-10-20 20:58 UTC, bernabe9 commented on src/containers/EditAdopterModal.js
> +        (<div className="animal-form-wrapper">
este parentesis se esta imprimiendo en la pantalla

2016-10-20 20:58 UTC, bernabe9 commented on src/containers/EditAdopterModal.js
> +        </div>);
lo mismo con este

2016-10-20 21:16 UTC, felparodi commented on src/containers/EditAdopterModal.js
> +      for (let name in myAdoter) {
no lo parce, lo limpia para no enviar cosas inecesrias

2016-10-20 21:18 UTC, felparodi commented on src/containers/EditAdopterModal.js
> +        home_address: '',
Eds asi para que sea del mismo formato que lo que recibo del servidor sino tengo que agregar como 3 lineias solo para asignar estas variabeles

2016-10-20 21:18 UTC, bernabe9 commented on src/containers/EditAdopterModal.js
> +      for (let name in myAdoter) {
Siempre hicimos que los parseos los haga las apis

2016-10-20 23:36 UTC, felparodi commented on src/containers/EditAdopterModal.js
> +      for (let name in myAdoter) {
no parcea quita lo que no se modifico que no es lo mismo

2016-10-21 00:11 UTC, bernabe9 approved these changes

2016-10-21 00:11 UTC, merged