Feed bugs feedbacks
pisgrupo9/ash_web pull request #124
Opened 2016-10-21 02:12 UTC by davidgivad

Se arreglaron los siguientes bugs:
https://trello.com/c/IND3V7BI/129-si-raza-es-un-campo-obligatorio-entonces-deberia-de-tener-la-marca
https://trello.com/c/Huk2kdTZ/123-si-en-los-filtros-de-busqueda-se-ingresa-especie-perro-y-luego-vacunados-si-y-castrados-si-y-se-da-click-en-buscar-se-realiza-el
https://trello.com/c/2bEuZAoB/150-bug-en-info-perfil-animal-cuando-el-animal-no-es-de-raza-perro-ni-gato-no-se-deberia-mostrar-vacunado-y-castrado
https://trello.com/c/GqQ8F7ek/120-en-listar-adoptantes-que-muestre-nombre-y-apellido

2016-10-21 02:34 UTC, bernabe9 requested changes

2016-10-21 02:34 UTC, bernabe9 commented on src/components/adopters/AdopterItem.js
> +            {adopter.blacklisted ? <div className="light-red">
mas facil:
```
<div className={adopter.blacklisted ? "light-red" : ""}>
  {adopter.first_name} {adopter.last_name}
</div>
```

2016-10-21 02:34 UTC, bernabe9 commented on src/components/animals/AnimalFilters.js
> +    debugger;
elimina esta linea

2016-10-21 02:34 UTC, bernabe9 commented on src/components/animals/AnimalFilters.js
> +    const changefield = (species_id == "1" || species_id == "2") && field == "species_id" && value != "1" && value != "2";
encapsula esto `(species_id == "1" || species_id == "2")` en una const booleana que sea `isAdoptable`

2016-10-21 02:34 UTC, bernabe9 commented on src/components/animals/AnimalFilters.js
> +      filter[ "castrated" ] = "";
usa dot notation

2016-10-21 02:34 UTC, bernabe9 commented on src/components/animals/AnimalFilters.js
> +      filter[ "vaccines" ] = "";
lo mismo

2016-10-21 02:34 UTC, bernabe9 commented on src/components/animals/AnimalForm.js
> +  let showRace = showCheckboxes || animal.species_id.toString() === "3";
mejor `showCheckboxes || animal.species_id === 3`

2016-10-21 02:34 UTC, bernabe9 commented on src/components/animals/perfil/AnimalEditForm.js
> +  let showRace = showCheckboxes || animal.species_id.toString() === "3";
lo mismo

2016-10-21 02:34 UTC, bernabe9 commented on src/components/animals/perfil/InfoPerfil.js
> +                  <td>{especieOption ? 'VACUNADO:' : ''}</td>
`CASTRADO`

2016-10-21 12:31 UTC, felparodi commented on src/components/animals/AnimalForm.js
> +  let showRace = showCheckboxes || animal.species_id === "3";
probate usar esta funcion del formValidateor "requiredRace'

2016-10-21 12:31 UTC, felparodi commented on src/components/animals/perfil/AnimalEditForm.js
> +  let showRace = showCheckboxes || animal.species_id === "3";
probate usar esta funcion del formValidateor "requiredRace'

2016-10-21 12:33 UTC, felparodi commented on src/components/animals/AnimalFilters.js
> +    const isAdoptable = species_id === "1" || species_id === "2" || species_id === "";
Buscate si no hay una funcion que resuelba esto

2016-10-22 00:43 UTC, bernabe9 approved these changes

2016-10-22 00:45 UTC, merged