Animal modal logout error
pisgrupo9/ash_web pull request #126
Opened 2016-10-21 21:30 UTC by joacolej

2016-10-22 00:38 UTC, bernabe9 commented
Como comentario estaria bueno buscar una solucion general a este problema, porque asi como pasa esto tambien pasa con los otros modals

2016-10-22 00:39 UTC, bernabe9 requested changes

2016-10-22 00:39 UTC, bernabe9 commented on src/containers/modal/NewAnimalModal.js
> +      window.location.replace("/login");
porque haces esto dos veces? Es decir, ya lo haces en la accion asi q nunca llegaria aca..

2016-10-23 14:03 UTC, joacolej commented
Creo que lo que hice en la acción me pareció una buena forma de solucionarlo. El hecho de que cuando recibe un authentication error haga history.push('/login')

Voy a ver si puedo encontrar una forma todavía más general pero lo dejo para el sprint que viene si querés que empiece con lo de listar animales de adoptante que me parece más necesario.

2016-10-24 00:43 UTC, bernabe9 approved these changes

2016-10-24 00:43 UTC, merged