Black List Button
pisgrupo9/ash_web pull request #129
Opened 2016-10-23 20:59 UTC by felparodi

![captura de pantalla de 2016-10-23 17 58 40](https://cloud.githubusercontent.com/assets/21043023/19629378/7c2f0bf0-994a-11e6-8637-bb830e37c260.png)

2016-10-23 23:24 UTC, bernabe9 commented
Detallesito visual:
Para los botones de `Cancelar` y `Agregar` usa el mismo estilo q el resto de los botones, a esto me refiero que el texto se mantenga blanco cuando se hace hover y que el color cambie a un gris mas fuerte y a un naranja mas fuerte.
Usa los scss q estan para el resto de los botones

2016-10-23 23:42 UTC, bernabe9 requested changes

2016-10-23 23:42 UTC, bernabe9 commented on src/components/adopters/perfil/AddToBlackListButton.js
> +                  title: message.ADD_BLACK_LIST_TITLE,
mal identado

2016-10-23 23:42 UTC, bernabe9 commented on src/actions/adopterActions.js
> +export const addToBlackListError= (response) => {
Esta accion no tiene sentido porque ningun reducer la esta escuchando. Para este caso me parece innecesario considerar el caso del error porque no se va a manipular

2016-10-23 23:42 UTC, bernabe9 commented on src/actions/adopterActions.js
> +      dispatch(addToBlackListError(err));
lo mismo sobre no manipular este error

2016-10-23 23:49 UTC, felparodi commented on src/actions/adopterActions.js
> +export const addToBlackListError= (response) => {
Si, al día de hoy que no hay restricciones para entra a la black list no tiene sentido, lo pensé si el día de mañana avía alguna. Queres que lo borre?

2016-10-23 23:51 UTC, bernabe9 commented on src/actions/adopterActions.js
> +export const addToBlackListError= (response) => {
Si sacalo, quedaria mas prolijo el codigo

2016-10-24 00:46 UTC, bernabe9 approved these changes

2016-10-24 00:46 UTC, merged