libreria + container de estadisticas
pisgrupo9/ash_web pull request #138
Opened 2016-10-26 21:59 UTC by joacolej

2016-10-26 22:00 UTC, bernabe9 commented on package.json
> +    "chart.js": "1.1.1",
No es suficiente con la libreria `react-chartjs`?

2016-10-26 22:02 UTC, bernabe9 requested changes

2016-10-26 22:02 UTC, bernabe9 commented on src/styles/statistics.scss
> +.profile-page-flex {
creo ya haber visto una clase con estas propiedades, si hiciste copy and paste, entonces usa `@extend`

2016-10-26 22:02 UTC, bernabe9 commented on src/styles/statistics.scss
> +.outer-flex {
lo mismo aca

2016-10-26 22:02 UTC, bernabe9 commented on src/styles/statistics.scss
> +.statistic-div {
lo mismo

2016-10-26 22:02 UTC, bernabe9 commented on src/styles/statistics.scss
> +.inner-flex {
lo mismo

2016-10-26 22:02 UTC, joacolej commented on package.json
> +    "chart.js": "1.1.1",
segui la guia de instalacion del "react-chart", de cualqueir forma no lo probe aun, ma;ana se viene la creme de la creme

2016-10-27 20:20 UTC, felparodi commented on src/containers/EstadisticasPage.js
> +                  {
mal indentado toda la lista, un solo tab mas que la declaracion de la varible

2016-10-27 20:43 UTC, closed without merging