fixed edit&export Buttons on animalPerfil
pisgrupo9/ash_web pull request #141
Opened 2016-10-27 03:09 UTC by davidgivad

Coloque Gruoup Buttons en AnimalPerfil
![screenshot from 2016-10-27 00-04-07](https://cloud.githubusercontent.com/assets/21270775/19753179/1984929a-9bd9-11e6-971f-10de1af22b64.png)

2016-10-28 00:49 UTC, bernabe9 commented
- Botones centrados
- No tan pegados al "ESTADO"

2016-10-28 00:52 UTC, bernabe9 requested changes

2016-10-28 00:52 UTC, bernabe9 commented on src/components/animals/perfil/EditAnimalButton.js
> +        <div className="btn-group" role="group">
que hace `role`?????

2016-10-28 00:52 UTC, bernabe9 commented on src/styles/styles.scss
> +  color: white;
`$white` si ya esta definida

2016-10-29 15:02 UTC, felparodi commented
No esta centrada en la ficha

2016-10-29 15:42 UTC, davidgivad commented
Sí esta, decime la medida de top left que queres.

2016-10-29 18:17 UTC, bernabe9 approved these changes

2016-10-29 18:17 UTC, bernabe9 commented on src/components/animals/perfil/EditAnimalButton.js
> +                      <div className="btn-group">
Utiliza el componente de bootstrap `<ButtonGroup />`, siempre es preferible que uses los componentes de bootstrap react antes que bootstrap pelado

2016-10-29 18:17 UTC, bernabe9 commented on src/components/animals/perfil/EditAnimalButton.js
> +      <div className="btn-group">
lo mismo

2016-10-29 18:17 UTC, bernabe9 commented on src/components/animals/perfil/EditAnimalButton.js
> +        <div className="btn-group">
lo mismo

2016-10-29 18:17 UTC, bernabe9 commented on src/components/animals/perfil/InfoPerfil.js
> +              <EditAnimalButton loading={loadingfunc} animal={animal} route_id={animalId} exportPerfil={exportPerfil} />
linea muy larga

2016-10-29 18:47 UTC, bernabe9 approved these changes

2016-10-29 18:47 UTC, merged