Se modifico el agregar a la black list
pisgrupo9/ash_web pull request #146
Opened 2016-10-30 23:31 UTC by felparodi

2016-10-30 23:52 UTC, bernabe9 requested changes

2016-10-30 23:52 UTC, bernabe9 commented on src/components/adopters/AdopterListWrapper.js
> +    this.setState({ filter });
No entiendo esto, en el state nunca se mantiene un filtro.. no veo la necesidad de este `setState`

2016-10-30 23:52 UTC, bernabe9 commented on src/components/adopters/AdopterListWrapper.js
> +    this.setState({ showBlacklist: !showBlacklist, loadingList: true, currPage: 1, filter });
aca me pregunto lo mismo

2016-10-30 23:52 UTC, bernabe9 commented on src/components/adopters/perfil/AddToBlackListButton.js
> +    let messageDialog = `${message.ADD_BLACK_LIST_MESSAGE}${adopter.animals.length ? message.ADD_BLACK_LIST_MESSAGE_HAVE_ANIMAL : ''}`;
este mensaje ya lo usaste, podrias hacer una funcion `const` en donde estan todos los mensajes que le pasas como parametro `adopter.animals.lenght` y te devuelva este mensaje

2016-10-30 23:56 UTC, felparodi commented on src/components/adopters/AdopterListWrapper.js
> +    this.setState({ filter });
para cuando recarga después del add to black list recargar la pagina, en el estado que estabas

2016-10-31 00:42 UTC, bernabe9 approved these changes

2016-10-31 00:42 UTC, merged