Estadisticas
pisgrupo9/ash_web pull request #150
Opened 2016-11-01 20:25 UTC by joacolej

2016-11-01 21:05 UTC, bernabe9 requested changes

2016-11-01 21:05 UTC, bernabe9 commented on package.json
> +    "chartjs": "0.3.24",
Segun la documentacion de react-chartjs esta libreria no es necesaria. Porque la agregaste?

2016-11-01 21:05 UTC, bernabe9 commented on src/actions/statisticActions.js
> +export const loadAdoptionStatistic = (date_start, date_finish) => {
siempre que sea posible usa camel case para las variables

2016-11-01 21:05 UTC, bernabe9 commented on src/api/statisticApi.js
> +  return arrayDate[2] + "/" + arrayDate[1] + "/" + arrayDate[0];
usa moment js para parsear dates

2016-11-01 21:05 UTC, bernabe9 commented on src/api/statisticApi.js
> +    labels: labels,
solo `labels` anda

2016-11-01 21:05 UTC, bernabe9 commented on src/styles/statistics.scss
> +  flex: 1 0 0;
aca esta porque no te debe andar en safari.. ese 0 del final esta muy turbio

2016-11-01 21:05 UTC, bernabe9 commented on src/util/validateForm.js
> +  let dateBegin = date_start.split('-');
asqueroso esto parece que estas programando en C, usa moment js
PD: con cariño

2016-11-01 21:05 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +      dates_adoption: {
camel case

2016-11-01 21:05 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +        start_date: '',
camel case

2016-11-01 21:05 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +        start_date: '',
camel case

2016-11-01 21:05 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +        end_date: '',
coma innecesaria

2016-11-01 21:05 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +    if (valid.validateDateStatistic(this.state.dates_adoption.start_date, this.state.dates_adoption.end_date)) {
Largo.
Acostumbrate a usar cosas como `let { start_date, end_date } = this.state.dates_adoption`

2016-11-01 21:05 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +      this.setState({ errors: errors });
solo `errors` alcanza

2016-11-01 21:05 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +      this.setState({ loadingBar: true });
usa el `setState` de arriba

2016-11-01 21:05 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +      let show_dates_adoption = {};
CAMEL CASEEEEE

2016-11-01 22:19 UTC, bernabe9 commented
Como comentario general me parece bastante mal que toda la logica de las graficas se maneje en `src/containers/EstadisticasPage.js` sobretodo porque va a haber otra grafica mas, es mas dificil de mantener. Lo correcto hubiera sido hacer un componente para cada grafica y que cada grafica maneje unicamente su logica.
Esto no es necesario que lo cambies pero estaria bueno

2016-11-01 22:30 UTC, bernabe9 requested changes

2016-11-01 22:30 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +      this.setState({ show_dates_adoption: show_dates_adoption });
solo `show_dates_adoption` deberia andar

2016-11-01 22:30 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +      let errors = { start_date: "El rango máximo es 3 meses",
los string de errores deberian estar guardados como constantes

2016-11-01 22:30 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +      this.setState ({ errors: errors });
solo `errors` deberia andar

2016-11-01 22:30 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +    this.setState({ dates_adoption });
usa el `setState` de arriba

2016-11-01 22:30 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +            <AnimalStatistic info={parseAnimalStat(this.props.animalStat)}
repetis mucho `this.props` y `this.state`, saca todas las variables que vayas a usar y te ahorras repetir tanto.
Ejemplo: `let { variable1, variable2 } = this.props`

2016-11-01 22:30 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +import { parseAdopterStat, parseAnimalStat } from '../api/statisticApi';
Esto es algo que esta sumamente prohibido. El componente de ninguna manera deberia saber de la existencia de la `api`. Se me ocurren dos posibles soluciones: 1) que se parseen los datos en la accion previamente a ser enviados al reducer(pienso que esta es la mas correcta y encapsula mejor). 2) que pongas las funciones de parse en un javascript que este en `util`

2016-11-01 22:30 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +    let dates_adoption = this.state.dates_adoption;
mejor `let { dates_adoption } = this.state`

2016-11-01 22:30 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +    let errors = this.state.errors;
lo mismo

2016-11-01 22:30 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +      adoptStat: state.statistic.adoptStat,
mal identado

2016-11-01 22:30 UTC, bernabe9 commented on src/reducers/statisticReducer.js
> +      return Object.assign({}, state, { adoptStat: adoptStat });
solo `adoptStat` deberia andar

2016-11-01 22:30 UTC, bernabe9 commented on src/reducers/statisticReducer.js
> +      return Object.assign({}, state, { animalStat: animalStat });
lo mismo

2016-11-01 23:30 UTC, bernabe9 commented
Feedback estetico:
1) En mobile se ve mal(la grafica dos se sale de la pantalla)
![screenshot from 2016-11-01 20-27-46](https://cloud.githubusercontent.com/assets/18464392/19911365/d9576bdc-a071-11e6-8a80-f95e84f0bb42.png)

2) Los contenedores de las graficas no deberian estar pegados
![screenshot from 2016-11-01 20-28-06](https://cloud.githubusercontent.com/assets/18464392/19911373/e81fcf9c-a071-11e6-96e6-9d1e1b8ed08f.png)

3) La flecha para refrescar la grafica 2 deberia estar alineada en el medio
![screenshot from 2016-11-01 20-28-23](https://cloud.githubusercontent.com/assets/18464392/19911377/f60b10d0-a071-11e6-8188-f522a5f89bd0.png)

2016-11-02 18:40 UTC, joacolej commented on src/reducers/statisticReducer.js
> +      return Object.assign({}, state, { adoptStat: adoptStat });
de hecho no

2016-11-02 21:08 UTC, bernabe9 requested changes

2016-11-02 21:08 UTC, bernabe9 commented on src/components/statistics/AdoptionStatistic.js
> +  let dateDecided = "Cantidad de animales adoptados del " + parseDate(showDates.startDate) + " al " + parseDate(showDates.endDate);
usa string interpolation

2016-11-02 21:08 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +    let { errors } = this.state;
usa el `let` de arriba

2016-11-02 21:08 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +      let errors = { startDate: messages.ERROR_STATISTIC_RANGE,
Mal identado.
Deberia ser:
```
  let errors = {
    startDate: messages.ERROR_STATISTIC_RANGE,
    endDate: messages.ERROR_STATISTIC_RANGE
  };
```

2016-11-02 21:08 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +      this.setState ({ errors: errors });
solo `errors` es suficiente

2016-11-03 01:51 UTC, bernabe9 commented on src/util/validateForm.js
> +  return moment(dateStart).add(3, 'months').isSameOrAfter(dateFinish);
se me pianta un lagrimon :+1:

2016-11-03 01:52 UTC, bernabe9 approved these changes

2016-11-03 02:06 UTC, merged