Se redirge al login cuando se pierde la seccion
pisgrupo9/ash_web pull request #151
Opened 2016-11-02 02:33 UTC by felparodi

Se redirige a login cuando se pierde la sección, ademas cuando se carga la pagina de login se  limpia todo el storge de la aplicación
Se cambio como se mueve entre aplicaciones sin romper el virtual-dome

2016-11-02 03:17 UTC, bernabe9 requested changes

2016-11-02 03:17 UTC, bernabe9 commented on src/api/apiService.js
> +        browserHistory.push('/login');
Porque aca en vez de hacer esto no llamas a: `loginInfo.CheckAuth()`?
Ademas de ahorrarte esta linea y la de abajo evitas tener que importar el `borwserHistory`, siempre se busca que este tipo de javascript(`apiService.js`) tenga bajo acoplamiento con la aplicación en si misma.

2016-11-02 03:17 UTC, bernabe9 commented on src/api/apiService.js
> +        toastr.error('ERROR', message.ERROR_INVALID_SESSION);
Este mensaje es poco representativo, porque aca en realidad se entra cuando hay un 401 osea un no autorizado, no necesariamente significa que la session sea invalida

2016-11-02 03:17 UTC, bernabe9 commented on src/actions/loginActions.js
> +export const cleanStore = () => {
Porque necesitas hacer un clean total del store?

2016-11-02 03:18 UTC, felparodi commented on src/api/apiService.js
> +        toastr.error('ERROR', message.ERROR_INVALID_SESSION);
Y como lo pondrías

2016-11-02 03:19 UTC, felparodi commented on src/actions/loginActions.js
> +export const cleanStore = () => {
para asegurarme de que no quede nada pendiente una ves que se pierda la seccion

2016-11-02 03:23 UTC, felparodi commented on src/api/apiService.js
> +        browserHistory.push('/login');
porque fue incremental, por eso quedo asi en principio  no se usaba el borwserHistory en CheckAuth() y se necesitaba un parámetro que no se tenia a nivel de apiService

2016-11-02 03:29 UTC, bernabe9 commented on src/actions/loginActions.js
> +export const cleanStore = () => {
Entiendo lo que decis pero de la forma que lo hiciste es inmantenible, si a cada reducer hay q hacerle un clean.
Si realmente queres reiniciar la aplicacion podrias usar `window.location('/login')` y de esa forma se recarga la aplicacion. Sino queres recargar la aplicacion podes usar algo mas aproximado a esto http://stackoverflow.com/questions/35622588/how-to-reset-the-state-of-a-redux-store

2016-11-02 03:32 UTC, bernabe9 commented on src/api/apiService.js
> +        toastr.error('ERROR', message.ERROR_INVALID_SESSION);
`Error: No autorizado`

2016-11-02 03:42 UTC, bernabe9 commented on src/actions/loginActions.js
> +export const cleanStore = () => {
Igual nosotros controlamos casi todo creo, los componentes que se tienen q limpiar generalmente tienen un clean cuando se desmontan, por eso no estoy seguro si podria llegar a quedar informacion colgada

2016-11-02 04:26 UTC, felparodi commented on src/actions/loginActions.js
> +export const cleanStore = () => {
capas que es de mas lo saco y pruebo

2016-11-02 11:52 UTC, felparodi commented on src/api/apiService.js
> +        browserHistory.push('/login');
Cambie como se asia porque de esa manera se trancaba el dom y hay una mejor

2016-11-03 00:15 UTC, felparodi commented on src/actions/loginActions.js
> +export const cleanStore = () => {
Tenias razón no era necesario, esta todo muy bien controlado para que no haya ruido

2016-11-03 00:25 UTC, bernabe9 approved these changes

2016-11-03 00:25 UTC, merged