Ayuda para los botones que son icons
pisgrupo9/ash_web pull request #156
Opened 2016-11-04 03:46 UTC by felparodi

Agrega tooltip a casi todo los iconos según el feedback
https://trello.com/c/VzxhkkCb/175-sugerencia-en-los-botones-con-forma-circular-como-editar-y-agregar-que-hay-para-agregar-nuevo-animal-o-adoptante-o-agregar-image
Miren bien ya que es un feedback de interno, si vale la pena que esto este asi

No acceptar a la liger y si no parece valido el feedback, archivarlo y cerrar el pr (no quiero corregir algo que no va)

2016-11-05 00:36 UTC, joacolej commented on src/constants/apiMessage.js
> +export const TOOLTIP_ADD_ANIMAL_EVENT = 'Crear Eveto';
Evento en vez de eveto

2016-11-05 00:36 UTC, joacolej commented on src/constants/apiMessage.js
> +export const TOOLTIP_ADD_ANIMAL_IMG = 'Agregar Imagenes';
imágenes

2016-11-05 00:36 UTC, joacolej commented on src/constants/apiMessage.js
> +export const TOOLTIP_ADD_ADOPTER_ANIAML = 'Adoptart Animales';
Animal, adoptar

2016-11-05 00:36 UTC, joacolej commented on src/constants/apiMessage.js
> +export const TOOLTIP_ADD_ADOPTER_BLACKLIST = 'Agrager a la lista negra';
agregar

2016-11-05 00:36 UTC, joacolej commented on src/constants/apiMessage.js
> +export const TOOLTIP_EDIT_ANIMAL_IMG = 'Editar Galeria';
galería va con tilde

2016-11-05 18:27 UTC, bernabe9 commented
Tiene un bug visual en los botones de editar animal:
Asi esta en tu pr:
![screenshot from 2016-11-05 15-24-51](https://cloud.githubusercontent.com/assets/18464392/20032597/32ce0ad4-a36c-11e6-9b7f-f1049d5b471b.png)
![screenshot from 2016-11-05 15-24-19]

Y asi esta en develop(bien):
(https://cloud.githubusercontent.com/assets/18464392/20032599/363d6a66-a36c-11e6-81c6-59b6a3f56cc9.png)

2016-11-05 18:30 UTC, bernabe9 commented
Sobre el pr:
Personalmente pienso que lo botones son super intuitivos y que no es necesario el tooltip, por mas que esta muy prolijo es como que molesta mucho.

Solo tendria sentido dejarlo si el cliente lo quiere. Lo que podemos hacer es que suba esta branch a amazon y que rodrigo le pregunte al cliente si le gusta

2016-11-06 19:00 UTC, bernabe9 requested changes

2016-11-06 19:00 UTC, bernabe9 commented on src/components/adopters/perfil/AddToBlackListButton.js
> +          onClick={this.addToBlackList}
esta y la propiedad de abajo estan mal ideantadas

2016-11-06 19:00 UTC, bernabe9 commented on src/containers/AnimalPerfilPage.js
> +                  onClick={this.editGallery}
esta propiedad y la de abajo estan mal identadas

2016-11-06 23:34 UTC, bernabe9 approved these changes

2016-11-06 23:37 UTC, merged