Se corrigen errores de las anteriores y se suma ultima estadistica
pisgrupo9/ash_web pull request #158
Opened 2016-11-04 21:09 UTC by joacolej

2016-11-04 21:21 UTC, bernabe9 requested changes

2016-11-04 21:21 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +      let startDateError = startDate === '' ? messages.ERROR_REQUIRED_FIELD : messages.ERROR_STATISTIC_RANGE;
mejor `startDate ? messages.ERROR_STATISTIC_RANGE : messages.ERROR_REQUIRED_FIELD;`

2016-11-04 21:21 UTC, bernabe9 commented on src/containers/EstadisticasPage.js
> +      let endDateError = endDate === '' ? messages.ERROR_REQUIRED_FIELD : messages.ERROR_STATISTIC_RANGE;
lo mismo analogo aca

2016-11-04 21:23 UTC, joacolej commented on src/containers/EstadisticasPage.js
> +      let startDateError = startDate === '' ? messages.ERROR_REQUIRED_FIELD : messages.ERROR_STATISTIC_RANGE;
el tema es que si es vacio que diga campo requerido.
STATISTIC_RANGE diria que el rango debe ser de 3 meses y eso no tiene sentido

2016-11-04 22:39 UTC, joacolej commented on src/containers/EstadisticasPage.js
> +      let startDateError = startDate === '' ? messages.ERROR_REQUIRED_FIELD : messages.ERROR_STATISTIC_RANGE;
ya entendi lo que queres decir, y si el string es vacio lo evalua como true

2016-11-04 22:41 UTC, joacolej commented on src/containers/EstadisticasPage.js
> +      let startDateError = startDate === '' ? messages.ERROR_REQUIRED_FIELD : messages.ERROR_STATISTIC_RANGE;
ta mala mia ya entendi lo que me querias decir jejeje

2016-11-05 18:08 UTC, bernabe9 requested changes

2016-11-05 18:08 UTC, bernabe9 commented on src/util/speciesUtils.js
> +  for (let i = 0; i < species.length; i++) {
mejor `for (let specie of species)`

2016-11-05 18:14 UTC, bernabe9 commented
Detalles visuales:
- En la ultima grafica el eje de las fechas queda pegado al final del contendor
- La ultima grafica deberia tener un poquito de margenes a los costados ocupa casi el 100% del width y height the contendor.
- En mobile: la ultima grafica esta pegada a la anterior

2016-11-07 14:28 UTC, bernabe9 approved these changes

2016-11-07 14:28 UTC, merged