Tests para el formulario de un animal
pisgrupo9/ash_web pull request #162
Opened 2016-11-06 17:01 UTC by Isa14

2016-11-06 19:07 UTC, bernabe9 requested changes

2016-11-06 19:07 UTC, bernabe9 commented on src/actions/animalActions.spec.js
> +//import { parseAnimal } from '../api/animalApi';
remove esta linea comentada

2016-11-06 19:07 UTC, bernabe9 commented on src/actions/animalActions.spec.js
> +      const expectedAction = { type: types.SEND_ANIMAL_FORM_SUCCESS, response: response };
solo `response` funciona

2016-11-06 19:07 UTC, bernabe9 commented on src/actions/animalActions.spec.js
> +      const expectedAction = { type: types.SEND_ANIMAL_FORM_ERROR, errors: errors };
solo `errors` funciona

2016-11-06 19:07 UTC, bernabe9 commented on src/actions/animalActions.spec.js
> +  //Me devuelve que las acciones son vacias, la store deberia tenerlas, esta bien lo que estoy haciendo?
entonces estos test no estan funcionales???

2016-11-06 19:07 UTC, bernabe9 commented on src/containers/modal/NewAnimalModal.js
> +export class NewAnimalModal extends Component {
No cambies esta linea

2016-11-06 19:07 UTC, bernabe9 commented on tools/testSetup.js
> +const jsdom = require('jsdom').jsdom;
no usas jsdom! deja este archivo como estaba

2016-11-14 01:45 UTC, bernabe9 requested changes

2016-11-14 01:45 UTC, bernabe9 commented on src/actions/animalActions.spec.js
> +        nock(consts.API_STAGING_URL)
este `nock` lo usas en este `it` y en el de arriba, fijate si podes correrlo para el `it` padre, luego de definir el animal

2016-11-14 01:45 UTC, bernabe9 commented on src/actions/animalActions.spec.js
> +        nock(consts.API_STAGING_URL)
lo mismo con este `nock`

2016-11-14 01:45 UTC, bernabe9 commented on src/actions/animalActions.spec.js
> +          weight: 15 };
el corchete `};` debe ir en la linea de abajo

2016-11-14 01:45 UTC, bernabe9 commented on src/actions/animalActions.spec.js
> +        const errors = { "birthdate": [ "La fecha de nacimiento es inválida."], "admission_date": ["La fecha de ingreso es inválida." ] };
separa esta linea en varias

2016-11-14 01:45 UTC, bernabe9 commented on src/containers/modal/NewAnimalModal.js
> +export class NewAnimalModal extends Component {
No cambies esta linea!

2016-11-14 01:45 UTC, bernabe9 commented on src/reducers/animalFormReducer.spec.js
> +  const getInitialState = () => {
usa el initialState real, no hardcodees uno

2016-11-14 01:45 UTC, bernabe9 commented on src/reducers/animalFormReducer.spec.js
> +    const action = { type: types.SEND_ANIMAL_FORM_ERROR, errors: errors };
solo `errors` es suficiente

2016-11-14 01:45 UTC, bernabe9 commented on src/reducers/animalFormReducer.spec.js
> +    const action = { type: types.SEND_ANIMAL_FORM_SUCCESS, response: response };
solo `response`

2016-11-14 01:45 UTC, bernabe9 commented on src/reducers/animalFormReducer.spec.js
> +    expect(animalFormReducer(getInitialState(), action)).to.deep.equal(expected);
que raro que este test te ande.. porque el `animalFormReducer` el estado inicial que estas comparando no es el correcto del que enrealidad tiene el `animalFormReducer`

2016-11-15 21:35 UTC, Isa14 commented on src/reducers/animalFormReducer.spec.js
> +    expect(animalFormReducer(getInitialState(), action)).to.deep.equal(expected);
mmmm

2016-11-16 12:01 UTC, bernabe9 requested changes

2016-11-16 12:01 UTC, bernabe9 commented on src/actions/animalActions.spec.js
> +          "birthdate": [ "La fecha de nacimiento es inválida."],
las propiedades que no sean strings.
Ademas usa single quotes

2016-11-16 12:01 UTC, bernabe9 commented on src/actions/animalActions.spec.js
> +          "admission_date": ["La fecha de ingreso es inválida." ]
lo mismo

2016-11-16 12:01 UTC, bernabe9 commented on src/reducers/animalFormReducer.spec.js
> +    expect(animalFormReducer(initialState, action)).to.deep.equal(expected);
esto no hace lo que dice el test: `Devuelve el estado inicial si ninguna acción coincide``

Cuando llamas al reducer no deberias pasarle nada, de esta forma el reducer va a tomar el initialState.

Algo asi:
```
it('Devuelve el estado inicial si ninguna acción coincide', () => {
  const action = { type: 'desconocida' };
  const expected = initialState.animalForm;
    
  expect(animalFormReducer(undefined, action)).to.deep.equal(expected);
});
```

2016-11-16 12:01 UTC, bernabe9 commented on src/actions/animalActions.spec.js
> +        nock('fake')
CUIDADO! este nock no esta funcionando y el test le esta pegando al servidor real, lo que hace que demore un monton e incluso a veces falle. Arregla este nock para que intercepte las requests

2016-11-16 12:01 UTC, bernabe9 commented on src/reducers/animalFormReducer.spec.js
> +  const getAppState = () => {
quizas no tenes claro el concepto de estado que se le pasa al reducer. Pero este no es un state valido o consistente con la app

2016-11-16 12:01 UTC, bernabe9 commented on src/reducers/animalFormReducer.spec.js
> +    expect(animalFormReducer(getAppState(), action)).to.deep.equal(expectedForm);
esta mal que le pases `getAppState()` poruqe no es un estado consistente

2016-11-16 12:01 UTC, bernabe9 commented on src/reducers/animalFormReducer.spec.js
> +    expect(animalFormReducer(getAppState(), action)).to.deep.equal(expectedForm);
lo mismo

2016-11-16 12:01 UTC, bernabe9 commented on src/reducers/animalFormReducer.spec.js
> +    expect(animalFormReducer(getAppState(), action)).to.deep.equal(expectedForm);
lo mismo

2016-11-16 22:59 UTC, bernabe9 requested changes

2016-11-16 22:59 UTC, bernabe9 commented on src/actions/animalActions.spec.js
> +        nock('consts.API_STAGING_URL')
sigue pegando al server real!!
seria: `nock(consts.API_STAGING_URL)`

2016-11-16 23:38 UTC, bernabe9 approved these changes

2016-11-16 23:44 UTC, merged