Fix ediatr Animal Perfil
pisgrupo9/ash_web pull request #168
Opened 2016-11-10 03:11 UTC by felparodi

Ver si el botón es necesario ya que ahora anda el click en la imagen y el drop zone

2016-11-11 23:43 UTC, bernabe9 requested changes

2016-11-11 23:43 UTC, bernabe9 commented on src/components/animals/perfil/AnimalEditForm.js
> +          <Input styleClass="profile-animal-input edit-input"
deja esta linea como estaba

2016-11-11 23:43 UTC, bernabe9 commented on src/styles/styles.scss
> +.edit-input {
elimina esta clase

2016-11-11 23:43 UTC, bernabe9 commented on src/components/animals/perfil/EditProfileDropzone.js
> +    let dropStyleClass = !preview ? 'profile-dropzone-not-bordes' : 'profile-dropzone';
mejor:
`let dropStyleClass = preview ? 'profile-dropzone' : 'profile-dropzone-not-bordes';`

2016-11-11 23:43 UTC, bernabe9 commented on src/components/animals/perfil/EditProfileDropzone.js
> +                      {!preview && perfImage}
esta linea y la de abajo las resumis:
`{preview ? picture : perfImage}`

2016-11-13 01:36 UTC, felparodi commented on src/components/animals/perfil/AnimalEditForm.js
> +          <Input styleClass="profile-animal-input edit-input"
eso fue por accidente jeje, era unas pruebas de una locura jaja que se marcaran los input modificados peor no es un requerimiento y me lolvide quitarlo

2016-11-13 18:43 UTC, bernabe9 approved these changes

2016-11-13 18:43 UTC, merged