Description text size, Image fix
pisgrupo9/ash_web pull request #170
Opened 2016-11-12 20:40 UTC by felparodi

https://trello.com/c/mfB928Lm/207-en-el-perfil-de-un-animal-el-titulo-de-galeria-deberia-estar-alineado-con-el-de-eventos
https://trello.com/c/zR1mLgtX/217-en-registrar-en-el-campo-numero-de-telefono-sigue-las-flechas-para-sumar-y-restar-numeros-lo-cual-no-funciona-bien-dado-que-los-
https://trello.com/c/Z9i8FTWE/214-si-la-foto-de-perfil-de-un-animal-es-vertical-se-sube-de-costado-y-la-vista-previa-de-imagenes-de-galeria-si-agregue-varias-foto
https://trello.com/c/hYrlGPP0/206-la-foto-de-perfil-de-un-animal-se-estira

2016-11-12 21:06 UTC, bernabe9 requested changes

2016-11-12 21:06 UTC, bernabe9 commented on src/components/common/ImagesPreview.js
> +            <div className="image-wrapper" key={image.name+Math.random()}>
En realidad esto no te asegura que no queden key duplicadas.. solo disminuye la probabilidad

2016-11-12 21:06 UTC, bernabe9 commented on src/styles/animal-form.scss
> +.animal-input.textarea {
coloca la clase `textarea` anidado dentro de `.animal-input`. Ademas cambia el nombre de la clase `textarea` , esta mal usar los elementos html como nombres de clases

2016-11-12 21:06 UTC, bernabe9 commented on src/styles/animal-perfil.scss
> +  max-height: 400px;
porque achicaste el max-height?

2016-11-12 21:06 UTC, bernabe9 commented on src/containers/AnimalPerfilPage.js
> -              <p className="section-title center">GALERÍA</p>
que pasa con la clase `section-title-center` sino se usa mas eliminala de scss

2016-11-12 21:13 UTC, bernabe9 requested changes

2016-11-12 21:13 UTC, bernabe9 commented on src/styles/images-dropzone.scss
> +  object-fit: cover;
no es necesario `object-fit` aca porque el contendor se adapta al tamaño de la foto

2016-11-13 01:18 UTC, felparodi commented on src/styles/animal-perfil.scss
> +  max-height: 400px;
es que porque con 440 es el tamaño con el que se sale de el contenedor los botones
420 quedan justo en el borde (que es re feo)  por eso 400

2016-11-13 01:23 UTC, felparodi commented on src/components/common/ImagesPreview.js
> +            <div className="image-wrapper" key={image.name+Math.random()}>
Pero ya se, pero es imposible que nos se dupliquen jamas (el las combinaciones de caracteres son finitas) si quered saco el comentario era para decir que ese random era con razon, 
Igual es mínima la probalbilida de que pase

2016-11-13 18:45 UTC, bernabe9 commented on src/styles/animal-perfil.scss
> +  max-height: 400px;
Lo correcto seria aumentar el max-height y a la vez agrandar el contenedor para que los botones no queden en el borde. 400 es muy chico cualquier foto sacada vertical del celular tiene mas largo que 400

2016-11-13 19:16 UTC, bernabe9 requested changes

2016-11-13 19:16 UTC, bernabe9 commented on src/components/common/ImagesPreview.js
> +            <div className="image-wrapper" key={image.name+Math.random()}>
Si usas la posicion del item dentro del array podes obtener una `key` unica para cada imagen

2016-11-14 01:32 UTC, bernabe9 commented on src/components/common/ImagesPreview.js
> +          {images.map((image, index) => (
excelente :+1:

2016-11-14 01:33 UTC, bernabe9 approved these changes

2016-11-14 01:33 UTC, merged