Se hicieron correcciones segun feedback
pisgrupo9/ash_web pull request #171
Opened 2016-11-12 20:59 UTC by joacolej

2016-11-12 21:25 UTC, bernabe9 requested changes

2016-11-12 21:25 UTC, bernabe9 commented on src/components/statistics/AnimalStatistic.js
> +      { loading ? '' : (<Legend info={info} />)}
mejor `{ !loading && (<Legend info={info} />)}`

2016-11-12 21:25 UTC, bernabe9 commented on src/components/statistics/AnimalStatistic.js
> +//{ loading ? '' : (<Legend info={info} />)}
elimina linea comentada

2016-11-12 21:25 UTC, bernabe9 commented on src/components/statistics/Legend.js
> +        return <div className="legend-item" key={label}><i className="material-icons color-round" style={{ color }}>fiber_manual_record</i> {label}</div>;
separa esta linea esta muy larga

2016-11-12 21:25 UTC, bernabe9 commented on src/components/statistics/Legend.js
> +      {info.map(function(infoItem) {
`function` ??? jaja usa javascript es6 arrow functions.
Algo asi:
```
(infoItem) => {
   blablabla
}
```

2016-11-12 21:25 UTC, bernabe9 commented on src/components/statistics/SpeciesStatistic.js
> +                label="F. Inicial"
Esta label deberia ser una cuando esta en web y otra cuando esta en mobile, a este componente le deberias inyectar una propiedad que sea `mobile` y segun ese atributo mostras una label o la otra

2016-11-12 21:25 UTC, bernabe9 commented on src/components/statistics/SpeciesStatistic.js
> +               label="F. Final"
lo mismo aca

2016-11-12 21:25 UTC, bernabe9 commented on src/styles/statistics.scss
> +  font-size: 10px;
por lo menos que sean de 12p

2016-11-12 21:27 UTC, bernabe9 commented
Comment de las fechas:

Me deberia mostrar los ultimos meses no??

![screenshot from 2016-11-12 18-26-12](https://cloud.githubusercontent.com/assets/18464392/20240968/8ef44992-a905-11e6-9754-e54a14a41694.png)
![screenshot from 2016-11-12 18-26-22](https://cloud.githubusercontent.com/assets/18464392/20240969/91c00d6e-a905-11e6-8962-6fd846d96482.png)

2016-11-12 23:24 UTC, joacolej commented on src/components/statistics/Legend.js
> +        return <div className="legend-item" key={label}><i className="material-icons color-round" style={{ color }}>fiber_manual_record</i> {label}</div>;
si separo esa linea se caga todo

2016-11-12 23:26 UTC, bernabe9 commented on src/components/statistics/Legend.js
> +        return <div className="legend-item" key={label}><i className="material-icons color-round" style={{ color }}>fiber_manual_record</i> {label}</div>;
whaat??

```
return (
  <div className="legend-item" key={label}>
    <i className="material-icons color-round" style={{ color }}>
      fiber_manual_record
    </i>
    {label}
</div>);
```

Eso tiene que andar

2016-11-13 00:41 UTC, bernabe9 requested changes

2016-11-13 00:41 UTC, bernabe9 commented on src/styles/statistics.scss
> +.legend-text {
esta clase no la usas en ningun lugar

2016-11-13 00:41 UTC, bernabe9 commented on src/styles/statistics.scss
> +  font-size: 10px;
deberia ser `12px`

2016-11-13 19:47 UTC, bernabe9 requested changes

2016-11-13 19:47 UTC, bernabe9 commented on src/styles/statistics.scss
> +  font-size: 11px !important;
Podes evitar este `important` si pones la clase anidada dentro de la clase `.legend-item`

2016-11-13 19:51 UTC, bernabe9 approved these changes

2016-11-13 20:01 UTC, merged