Edit animal perfil
pisgrupo9/ash_web pull request #52
Opened 2016-09-22 05:37 UTC by davidgivad

Se creo Modal para editar perfil de un animal. 
![screenshot from 2016-09-22 02-36-54](https://cloud.githubusercontent.com/assets/21270775/18737953/77c16568-806d-11e6-8b9b-9fbc7d438b0d.png)
![screenshot from 2016-09-22 02-37-00](https://cloud.githubusercontent.com/assets/21270775/18737954/77c7e9b0-806d-11e6-8090-bfad9070bd55.png)

2016-09-22 21:02 UTC, bernabe9 commented
Correcciones visuales:
1- El boton para editar lo tenes que hacer examente igual que en el diseño:
![screenshot from 2016-09-22 17-48-02](https://cloud.githubusercontent.com/assets/18464392/18765596/c5254c46-80ec-11e6-90f8-fa54c5c392e2.png)

2- La seccion info perfil debe tener el mismo largo que la suma de las secciones eventos y galeria
3- Hay q scrollear para ver toda la info basica, esto es poco practico, la seccion info basica se deberia ver en la pantalla sin tener que bajar ( quizas disminuyendo un poco la imagen de perfil y juntando los campos)
4- El modal de editar esta totalmente desproporcionado. El campo para cambiar la imagen de perfil tiene mucho espacio en blanco, la primer fila tiene 4 columnas y la segunda 3. Aprovecha mejor los espacios y hacelo mas proporcionado.
5- En el modal de editar animal, los campos "vacunado" y "castrado" hacelos que sean checkboxes para mantenerlo consistente con el alta animal
6- No hay spinner de loading 

Correcciones funcionales:
- Todos los campos son modificables

2016-09-22 21:03 UTC, bernabe9 commented on src/actions/animalActions.js
> +export const editAnimaSucces = () => {
seria `editAnimalSuccess`

2016-09-22 21:04 UTC, bernabe9 commented on src/actions/animalActions.js
> +export const editAnimaError = (errors) => {
seria `editAnimalError`

2016-09-22 21:07 UTC, bernabe9 commented on src/components/animals/InfoPerfil.js
> +  let EspecieOption = animal.species == "Perro" || animal.species == "Gato";
las variables deben comenzar con minuscula, aca seria `especieOption`.
Ademas debes comparar con el `id` y no con el string

2016-09-22 21:10 UTC, bernabe9 commented on src/components/animals/InfoPerfil.js
> +                <td>{EspecieOption && (animal.vaccines ? <font color="green"> SI </font> : <font color="red"> NO </font>)}</td>
linea muy larga que perfectamente se puede separar en varias

2016-09-22 21:10 UTC, bernabe9 commented on src/components/animals/InfoPerfil.js
> +                <td>{EspecieOption && (animal.castrated ? <font color="green"> SI </font> : <font color="red"> NO </font>)}</td>
lo mismo aca

2016-09-22 21:11 UTC, bernabe9 commented on src/components/animals/InfoPerfil.js
> +  styleClass: string.isRequired
en un componente, un `styleClass` nunca deberia ser requerido, porque necesitaste que sea requerido?

2016-09-22 21:12 UTC, bernabe9 commented on src/styles/animal-perfil.scss
> +  width : 120%;
No se usan porcentajes por arriba del `100%` en todo caso agrandas el elemento padre

2016-09-22 21:12 UTC, bernabe9 commented on src/styles/animal-perfil.scss
> +    width: 115%;
No se usan porcentajes por arriba del `100%` en todo caso agrandas el elemento padre

2016-09-22 21:14 UTC, bernabe9 commented on src/styles/animal-perfil.scss
> +  margin-left: 270px;
no utilices margenes para mover elementos hacia la derecha, usa `float: right`

2016-09-22 21:20 UTC, bernabe9 commented on src/containers/AnimalPerfil.js
> +  edit() {
Porque esta funcion?

2016-09-22 21:20 UTC, bernabe9 commented on src/containers/AnimalPerfil.js
> +  onClose() {
porque esta funcion?

2016-09-22 21:21 UTC, bernabe9 commented on src/containers/AnimalPerfil.js
> +                                edit={this.edit}
Porque le pasas `edit` y todos los siguientes campos si lo estas editando desde el modal?

`AnimalPerfil` ya estaba hecho no entiendo porque lo cambiaste.
Ademas `AnimalPefil` NO es un contenedor, es un componente

2016-09-22 21:28 UTC, bernabe9 commented on src/containers/AnimalPerfilPage.js
> +  onOpen() {
De aca para abajo toda esta funcionalidad no esta en el lugar correcto, deberia ir en el modal.
El container `AnimalPerfilPage` deriva hacia a la info basica del animal, los eventos y la galeria.
Si pusieramos la funcionalidad de esas 3 cosas en `AnimalPefilPage` seria muy confuso y poco eficiente

2016-09-22 21:30 UTC, bernabe9 commented on src/containers/EditAnimalModal.js
> +  let fecha_cumple = animal.birthdate && animal.birthdate.length == 10 ? animal.birthdate.substring(0, animal.birthdate.length - 3) : animal.birthdate;
linea muy larga

2016-09-22 21:31 UTC, bernabe9 commented on src/components/common/SelectInput.js
> +const SelectInput = ({ styleClass, name, label, onChange, defaultOption, value, error, options, edit }) => {
Cual es la necesidad de modificar este componente?
Ademas ponerle un parametro `edit` que sea requerido limita practicidad.

2016-09-22 21:34 UTC, bernabe9 commented on src/styles/animal-form.scss
> +.profile-animal-input {
Ya existe la clase `.animal-input` que es exactamente igual a `.profile-animal-input` estas duplicando css

2016-09-22 21:37 UTC, bernabe9 commented on src/styles/animal-perfil.scss
> +  border: 2px solid $grey;
estas repitiendo estilos, como estaba antes se reutilizaba. 
Lo que podes hacer es definir una base tipo `section-div`  que sean las que todos usan: 
```
.section-div {
    border: 2px solid $grey;
    background-color: white;
    margin-bottom: 5px;
    padding: 5px;
}
```
y de ahi extender todas las demas

2016-09-22 21:38 UTC, bernabe9 requested changes

2016-09-22 22:49 UTC, davidgivad commented on src/components/animals/InfoPerfil.js
> +  let EspecieOption = animal.species == "Perro" || animal.species == "Gato";
Habria que pedir a Backend que nos dé id de especie, ahora solo nos da nombre de especie. Para mi no cambia mucho comparar con nombre de especie.

2016-09-23 01:03 UTC, bernabe9 commented on src/components/animals/InfoPerfil.js
> +  let EspecieOption = animal.species == "Perro" || animal.species == "Gato";
Esta bien, en info animal vos solo tenes esa informacion, dejalo como esta

2016-09-23 01:35 UTC, davidgivad commented on src/containers/AnimalPerfil.js
> +  edit() {
Esta pagina no existe

2016-09-23 01:36 UTC, davidgivad commented on src/containers/AnimalPerfil.js
> +  onClose() {
Esta pagina no existe me olvide borrarla

2016-09-23 01:36 UTC, davidgivad commented on src/containers/AnimalPerfil.js
> +                                edit={this.edit}
Esta pagina no existe

2016-09-23 02:00 UTC, davidgivad commented on src/containers/AnimalPerfilPage.js
> +  onOpen() {
Entiendo lo que decis y es discutible. Se tendria pasar muchos parametros al componente modal y esto va generar muchos flujos y pasaría lo mismo en el componente Modal.

2016-09-23 02:06 UTC, davidgivad commented on src/styles/animal-form.scss
> +.profile-animal-input {
problema de mergeo

2016-09-23 02:08 UTC, davidgivad commented on src/components/common/SelectInput.js
> +const SelectInput = ({ styleClass, name, label, onChange, defaultOption, value, error, options, edit }) => {
Lo uso para que no haya opcion vacia.

2016-09-23 14:38 UTC, bernabe9 commented on src/components/common/SelectInput.js
> +const SelectInput = ({ styleClass, name, label, onChange, defaultOption, value, error, options, edit }) => {
para eso existe el defaultOption... no es necesario modificar este componente

2016-09-23 14:39 UTC, bernabe9 commented on src/containers/AnimalPerfilPage.js
> +  onOpen() {
Colocar aca la funcionalidad es un ERROR, pasar muchos parametros no es algo malo y pasar muchos flujos es en lo q se basa react, pasar flujos hacia los hijos

2016-09-23 14:39 UTC, bernabe9 requested changes

2016-09-23 23:24 UTC, felparodi approved these changes

2016-09-23 23:24 UTC, felparodi commented on src/components/animals/InfoPerfil.js
>                </tr>
Esto no tiene sentido sea EspecioOption o no se muestra los campos de la tabla en caso de no ser EspeciOption solo aparecen vacíos, Tiene alguna razón eso?

2016-09-23 23:24 UTC, felparodi commented on src/components/common/SelectInput.js
> +          {edit ? '' : <option value="">{defaultOption}</option>}
Porque el ternario con el edit  en ves de {!edit && ....}
Otra cosa porque se solo se oculta la primera opción y no todas las demás cuando esta en edit true?

2016-09-23 23:24 UTC, felparodi commented on src/containers/AnimalPerfil.js
> +          )}
SI los dos bloques solo se diferencia en la propiedad animal porque el ternario los escribe todo devuelta envés de solo definir la propiedad animal con que valor se realiza

2016-09-23 23:24 UTC, felparodi commented on src/components/animals/EditAnimalButton.js
> +import React, { Component, PropTypes } from 'react';
Nunca usas El componete EditarAnimalButton

2016-09-26 21:11 UTC, bernabe9 commented on src/styles/animal-form.scss
> +
linea innecesaria

2016-09-26 21:11 UTC, bernabe9 commented on src/styles/styles.scss
> +
linea innecesaria

2016-09-26 21:11 UTC, bernabe9 commented on src/styles/styles.scss
> +body{margin:40px;}
espacio entre los brackets

2016-09-26 22:51 UTC, bernabe9 commented on src/components/common/SelectInput.js
> +      {label && <label className="input-label" htmlFor={name}>{label}</label>}
En todos los `Select Box` que utilizas le pasas una `label` , mientras no necesitemos sacarla dejala como estaba.

2016-09-26 22:51 UTC, bernabe9 commented on src/components/common/SelectInput.js
> +  label: string,
En todos los `Select Box` que utilizas le pasas una `label` , dejala como `isRequired`

2016-09-26 22:51 UTC, bernabe9 requested changes

2016-09-26 23:23 UTC, bernabe9 requested changes

2016-09-26 23:23 UTC, bernabe9 commented on src/api/animalApi.js
> +  if (parseAnimal.birthdate != undefined) {
Como puede pasar que `birthdate` sea `undefined` si es un campo obligatorio???

2016-09-26 23:23 UTC, bernabe9 commented on src/components/animals/AnimalEditForm.js
> +  let showCheckboxes = animal.species_id == "1" || animal.species_id == "2";
usa `===` en lugar de `==`

2016-09-26 23:31 UTC, davidgivad commented on src/api/animalApi.js
> +  if (parseAnimal.birthdate != undefined) {
Yo pregunto lo mismo.

2016-09-26 23:33 UTC, davidgivad commented on src/api/animalApi.js
> +  if (parseAnimal.birthdate != undefined) {
Yo cuando uso PUT envio solo los campos que se modifican y los demas campos no se envian

2016-09-26 23:33 UTC, bernabe9 commented on src/api/animalApi.js
> +  if (parseAnimal.birthdate != undefined) {
Esa validacion es innecesaria porque nunca puede suceder si validas previamente que no pueda ser vacio

2016-09-27 00:33 UTC, bernabe9 commented
Lista de correcciones:
1- Mostrar 3 campos por fila
2- Proporcionar foto de perfil
3- Agregar spinner(el tiempo que requiere cuando se agrega foto de perfil es mucho)
4- Cuando un animal ya es `Perro` y le doy editar no aparecen los campos `vacunas` ni `castrado`
5- Cuando le doy editar no aparece el `sexo` actual del animal marcado

2016-09-27 12:09 UTC, bernabe9 approved these changes

2016-09-27 12:09 UTC, merged