Se agrega lista de animales
pisgrupo9/ash_web pull request #53
Opened 2016-09-23 19:16 UTC by joacolej

![pranimallist](https://cloud.githubusercontent.com/assets/16958182/18798474/10bfaa7c-81a9-11e6-91b0-a4dbf66cc98c.png)
![pranimallist](https://cloud.githubusercontent.com/assets/16958182/18798475/10c67500-81a9-11e6-8cec-2869e09f349e.png)

2016-09-23 21:43 UTC, joacolej commented on src/components/animals/AnimalItem.js
> +        <div className="animal-state-species"> {animal.id % 2 === 1 ? adopt : notAdopt} </div>
Esto lo hice para que se vea visualmente, aunque la logica no este implementada

2016-09-23 21:44 UTC, felparodi commented on src/components/animals/AnimalListWrapper.js
> +
Linea ineseaeria

2016-09-23 21:45 UTC, felparodi commented on src/components/animals/AnimalListWrapper.js
> +
Linea Inesezaria

2016-09-23 21:55 UTC, felparodi commented on src/components/animals/AnimalItem.js
> +        <div className="animal-state-species"> {animal.species_id} </div>
No deberia ser el nombre de la sepecier?

2016-09-24 00:08 UTC, bernabe9 commented
Respecto al diseño, esta muy bien logrado y prolijo.

Un detalle que encontre:
![screenshot from 2016-09-23 21-01-37](https://cloud.githubusercontent.com/assets/18464392/18804438/48aa8178-81d1-11e6-951a-65bf411a9d8b.png)

Si el nombre del animal es muy grande se ve mal en el mobile. Se me ocurre que se puede solucionar usando : `max-width: 30%`, el 30% es a modo de ejemplo, tambien tendrias q ocultar el `overflow` hay formas de hacerlo con puntos suspensivos, osea que si el animal se llama `matiasssssss` cuando el nombre supera el campo entonces aparece `matiass...`, esto de los puntos suspensivos tambien es a modo de sugerencia. Podes resolverlo como quieras vos, lo q no puede pasar es que quede como la captura que te adjunte

2016-09-24 14:14 UTC, bernabe9 commented on src/components/animals/AnimalItem.js
> +        <div className="animal-state-species"> {animal.species_id} </div>
Estoy de acuerdo con @felparodi, deberias obtener las especies previamente para luego comparar los `id` y obtener asi el nombre de la especie

2016-09-24 14:18 UTC, bernabe9 commented on src/components/animals/AnimalListWrapper.js
> +
Separar el `state` de las funciones con una linea no me parece q este mal. Le da claridad

2016-09-24 14:22 UTC, bernabe9 commented on src/components/animals/AnimalListWrapper.js
> +    this.setState({ selectedAnimalId: this.state.selectedAnimalId === animalId.toString() ? '' : animalId.toString() });
Para mayor claridad, separalo en dos lineas. Una `const` que contenga la condicion que se debe cumplir y abajo lo otro, algo asi seria:
```
const equalsId = this.state.selectedAnimalId === animalId.toString();
this.setState({ selectedAnimalId: equalsId ? '' : animalId.toString() });
```

2016-09-24 14:28 UTC, bernabe9 commented on src/styles/animal-list.scss
> +  margin-bottom: 20px;
Cuando definis varios margenes(bottom, left, right) existe una abreviatura:
`margin: top right bottom left` (pensa en el sentido de un reloj)
donde segun corresponda le pones los valores.
En este caso te quedaria:
`margin: 0 20px 20px 20px`

2016-09-24 14:31 UTC, bernabe9 commented on src/styles/animal-list.scss
> +  .animal-item-container:hover {
en esta clase y en la de abajo tienen un tab de mas

2016-09-24 14:39 UTC, bernabe9 commented on src/styles/animal-list.scss
> +  .link-style:hover {
un tab de mas

2016-09-24 14:39 UTC, bernabe9 requested changes

2016-09-24 20:03 UTC, joacolej commented on src/components/animals/AnimalListWrapper.js
> +    this.setState({ selectedAnimalId: this.state.selectedAnimalId === animalId.toString() ? '' : animalId.toString() });
todo sea por sumar lineas

2016-09-24 20:05 UTC, bernabe9 commented on src/components/animals/AnimalListWrapper.js
> +    this.setState({ selectedAnimalId: this.state.selectedAnimalId === animalId.toString() ? '' : animalId.toString() });
Si queres escribir en pocas lineas y desproijo te invito a programar en C++

2016-09-24 21:32 UTC, bernabe9 approved these changes

2016-09-24 21:32 UTC, merged