view mini perfil integrado en Lista
pisgrupo9/ash_web pull request #61
Opened 2016-09-25 07:25 UTC by davidgivad

Se agrego mini vista de perfil de un animal.
![screenshot from 2016-09-25 04-24-01](https://cloud.githubusercontent.com/assets/21270775/18813666/1d2cffd2-82d8-11e6-92da-c174ec071dfe.png)

2016-09-26 21:44 UTC, bernabe9 commented
Correcciones:

- Agregar el campo `nombre` en los animales
- Falta el borde entre la columna `Sexo` y `Castrado`

2016-09-26 21:44 UTC, bernabe9 commented on src/components/animals/AnimalItem.js
> +        <div>
necesitas este `div` ?

2016-09-26 21:45 UTC, bernabe9 commented on src/styles/animal-perfil.scss
> +  padding: 10px 30px 10px 30px;
Se puede simplificar como: `padding: 10px 30px;`

2016-09-26 21:45 UTC, bernabe9 commented on src/styles/animal-perfil.scss
> +  text-align:center;
espacio entre `:` y `center`

2016-09-26 21:46 UTC, bernabe9 commented on src/components/animals/MiniInfoPerfil.js
> +      <img className={'mini-perfil-image'} src="https://images-na.ssl-images-amazon.com/images/G/01/img15/pet-products/small-tiles/23695_pets_vertical_store_dogs_small_tile_8._CB312176604_.jpg" />
Usa la imagen real que traes de la api

2016-09-26 21:46 UTC, bernabe9 requested changes

2016-09-27 00:24 UTC, davidgivad commented on src/components/animals/AnimalItem.js
> +        <div>
Es para que funcione correctamente Collapse.

2016-09-27 00:44 UTC, bernabe9 requested changes

2016-09-27 00:44 UTC, bernabe9 commented on src/components/animals/AnimalList.js
> +      )};
El `;` no va, aparece como texto en la pantalla.
![ddd](https://cloud.githubusercontent.com/assets/18464392/18856588/5e9c6d58-8432-11e6-88dd-23f9d8154662.png)

2016-09-27 00:56 UTC, bernabe9 approved these changes

2016-09-27 00:59 UTC, merged