Coneccion y reducer comunication
pisgrupo9/ash_web pull request #70
Opened 2016-09-29 03:18 UTC by felparodi

La función parecer el filtro  de animales devuelve siempre vacio porque aun no se definio el backend
![captura de pantalla de 2016-09-29 00 17 54](https://cloud.githubusercontent.com/assets/21043023/18939889/455b8fe6-85da-11e6-8d78-7d95cd81c4dd.png)
![captura de pantalla de 2016-09-29 00 18 14](https://cloud.githubusercontent.com/assets/21043023/18939890/455c9828-85da-11e6-8682-3ed7562ac227.png)

2016-09-29 12:04 UTC, bernabe9 commented
Correcciones visuales:
-  El titulo de `filtro` no esta igual al diseño
![captura de pantalla 2016-09-29 a las 8 58 41 a m](https://cloud.githubusercontent.com/assets/18464392/18953069/f92c580a-8622-11e6-80e5-9f52c9c2a463.png)

- El texto de `Fec. Nacimiento` fijate que el color este dentro de los grises/negros que tenemos en nuestra paleta de colores.

- Texto placeholder alineado al centro( esta respuesta capaz ayuda http://stackoverflow.com/questions/7381446/center-html-input-text-field-placeholder)

- Sacale el color ese azul que tiene cuando se hace focus sobre un input o cambialo por un color acorde con la paleta de colores

- Pone el campo `Nombre` antes que el campo `Numero de chip`

2016-09-29 12:23 UTC, bernabe9 requested changes

2016-09-29 12:23 UTC, bernabe9 commented on src/api/animalApi.js
> +  return filter ? '' : '';
Que hace esto??? Te devuelve siempre `''`

2016-09-29 12:23 UTC, bernabe9 commented on src/components/animals/AnimalFilters.js
> +    let filter = {};
ojo la identacion

2016-09-29 12:23 UTC, bernabe9 commented on src/components/animals/AnimalFilters.js
> +          filter[name] = this.state.filter[name];
aca y en la linea de abajo tambien

2016-09-29 12:23 UTC, bernabe9 commented on src/components/animals/AnimalFilters.js
> +    if (this.state.filter[name] != "") {
El hecho de quitar los parametros que tienen string vacio me parece que estaria mejor ponerlo en `parseFilter`

2016-09-29 12:23 UTC, bernabe9 commented on src/components/animals/AnimalFilters.js
> +    const genders = [ { id: "male", name: "Macho" },
considerando que esta constante se esta usando mucho capaz que estaria bueno incluirla en alguno de los archivos de constantes( por ejemplo `apiConstants`)

2016-09-29 12:23 UTC, bernabe9 commented on src/styles/animal-list.scss
> +    padding: 0 10px 0 10px;
abreviatura: `padding: 0 10px;`

2016-09-29 12:23 UTC, bernabe9 commented on src/styles/animal-list.scss
> +        color: rgba(0,0,0,0);
en lo posible usa colores en hexadecimales, o aca mejor aun `black`

2016-09-29 12:23 UTC, bernabe9 commented on src/styles/animal-list.scss
> +  margin-right: 10px;
usa abreviatura para margin, tenes 3 margenes `buttom' , `right` y `left` definidos

2016-09-29 14:31 UTC, felparodi commented on src/api/animalApi.js
> +  return filter ? '' : '';
Porque como no esta definido como van a ser los parametros apartir de los filtros la function esta esta incompleta, y si una variable no se usa da error y queria dejar el esqueleto lo mas completo posible

2016-09-29 14:32 UTC, felparodi commented on src/components/animals/AnimalFilters.js
> +    if (this.state.filter[name] != "") {
Podria ser, pero no esta mal que se haga aca

2016-09-29 14:35 UTC, felparodi commented on src/styles/animal-list.scss
> +        color: rgba(0,0,0,0);
EL caso que este color es trasparente que en hexadecimal no lo compila correctamente
ya que que no acepta #00000000 o  a mi me tira error eso

2016-10-02 04:39 UTC, bernabe9 approved these changes

2016-10-02 15:39 UTC, merged