Show event animal
pisgrupo9/ash_web pull request #74
Opened 2016-10-02 02:12 UTC by davidgivad

Show de event Animal. Dos cosas que tengo que arreglar que no pude arreglar aun, si alguien me tira algun pique se agradece.
1. El componente lista de eventos sea scroleable. asi la lista no sigue yendo pa abajo.
2. Un bug, la lista no queda limpia. cuando veo lista de eventos de un animal luego al mirar la de otro animal, la lista vieja se queda mostrandose. No se cual es problema.

2016-10-02 02:46 UTC, felparodi commented
2. Para corregir ese bug tenes que poner en el reduce de eventos que cuando escucha el evento getAnimal( SHOW_ANIMAL_PROFILE) se vacié la lista de eventos

2016-10-02 17:48 UTC, bernabe9 requested changes

2016-10-02 17:48 UTC, bernabe9 commented on src/components/animals/AnimalEventWrapper.js
> +    this.props.actions.loadEvents(this.props.route_id, 4, 1);
usa variables del state para el 4 y 1, para el uno podes usar `currPage`

2016-10-02 17:48 UTC, bernabe9 commented on src/components/animals/AnimalEventWrapper.js
> +    this.setState({ currPage: nextPage });
esta linea y la de abajo no podes juntarlas?

2016-10-02 17:48 UTC, bernabe9 commented on src/components/animals/AnimalEventWrapper.js
> +    this.props.actions.loadEvents(this.props.route_id, 3, nextPage);
deberias pedir siempre la misma cantidad, la primera vez pediste 4 y ahora 3

2016-10-02 17:48 UTC, bernabe9 commented on src/components/animals/EventList.js
> +  const spinner = (<div className="spinner"> <Spinner spinnerName="three-bounce" noFadeIn /> </div>);
usa el componente `SpinnerComponent`

2016-10-02 17:52 UTC, bernabe9 commented
![screenshot from 2016-10-02 14-46-37](https://cloud.githubusercontent.com/assets/18464392/19022466/cd7f9b7e-88af-11e6-9a4c-234e903ef0a3.png)

Me salta este error cuando pido mas eventos

2016-10-02 17:52 UTC, bernabe9 commented
Todavia le falta mucho visualmente, que quede IGUAL que el diseño!

2016-10-02 21:57 UTC, joacolej commented on src/components/animals/AnimalEventHeader.js
> +        <div className="animal-header-title title">BUSQUEDA EVENTOS</div>
Búsqueda va con tilde

2016-10-02 21:57 UTC, joacolej commented on src/components/animals/AnimalEventHeader.js
> +        <div className="float-right"><p>BOTON agregar EVENTO</p></div>
Botón también, pero igual no se si esto se ve

2016-10-02 21:57 UTC, joacolej commented on src/components/animals/EventItem.js
> +import '../../styles/animal-list.scss';
me parece que no esta bueno importar los estilos de varias cosas, creo que deberias hacer los estilos aparte y no importar todo.

2016-10-02 21:57 UTC, joacolej commented on src/reducers/initialState.js
> +    events: []
es necesario un objeto que tenga adentro un array?

2016-10-02 22:03 UTC, davidgivad commented on src/components/animals/AnimalEventHeader.js
> +        <div className="animal-header-title title">BUSQUEDA EVENTOS</div>
No va ir

2016-10-02 22:03 UTC, davidgivad commented on src/components/animals/AnimalEventHeader.js
> +        <div className="float-right"><p>BOTON agregar EVENTO</p></div>
No va ir

2016-10-02 22:04 UTC, davidgivad commented on src/reducers/initialState.js
> +    events: []
Despues le agrego mas cosas al events

2016-10-03 00:25 UTC, bernabe9 requested changes

2016-10-03 00:25 UTC, bernabe9 commented on package.json
> +    "react-infinite": "0.9.2",
Elimina infinite si no se usa mas

2016-10-03 00:25 UTC, bernabe9 commented on src/styles/animal-list.scss
> +  overflow: scroll;
utiliza `overflow: auto` para evitar que se muestre el scroll cuando no es necesario

2016-10-03 00:25 UTC, bernabe9 commented on src/components/animals/EventItem.js
> +import '../../styles/animal-list.scss';
No es malo reutilizar.. Pienso que cuantos mas import tenga tu componente mas estas reutilizando

2016-10-03 00:37 UTC, bernabe9 requested changes

2016-10-03 00:37 UTC, bernabe9 commented on src/components/animals/AnimalEventWrapper.js
> +    this.state = { selectedEventId: '',
baja a la linea de abajo las propiedades

2016-10-03 00:37 UTC, bernabe9 commented on src/components/animals/EventList.js
> +          <EventItem event={event} key={event.id}
una propiedad por linea

2016-10-03 00:44 UTC, bernabe9 requested changes

2016-10-03 00:44 UTC, bernabe9 commented on src/styles/animal-list.scss
> +  font-weight: 450;
no existe esta `font-weight`

2016-10-03 00:48 UTC, bernabe9 commented
@davidgivad todos los componentes que tengan que ver con los eventos colocalos en `/components/animals/events` para mayor organizacion del proyecto

2016-10-03 00:53 UTC, bernabe9 requested changes

2016-10-03 00:53 UTC, bernabe9 commented on src/actions/animalActions.js
> +export const loadEventsSuccess = (response) => {
estas dos acciones deberian ir en el `actions/eventActions`

2016-10-03 00:53 UTC, bernabe9 commented on src/actions/animalActions.js
> +export const loadEvents = (animal_id, row, col) => {
lo mismo que arriba

2016-10-03 00:53 UTC, bernabe9 commented on src/actions/animalActions.js
> +export const showEvent = (animal_id, event_id) => {
lo mismo q arriba

2016-10-03 00:53 UTC, bernabe9 commented on src/api/animalApi.js
> +  static getEvents(id_animal, row, col) {
esto y lo de abajo va en `eventApi`

2016-10-03 13:33 UTC, felparodi commented on src/components/animals/events/AnimalEventHeader.js
> +const AnimalEventHeader = (id_route) => {
Porque pasas un objeto cuando solo necesitas un campo de el mismo?
queda no muy limpio? porque no le ponses que llegue solo el animal id

2016-10-03 14:24 UTC, davidgivad commented on src/components/animals/events/AnimalEventHeader.js
> +const AnimalEventHeader = (id_route) => {
Corregido

2016-10-03 16:46 UTC, felparodi commented
Esta muy Feo Visualmente el view del evento

<img width="972" alt="screen shot 2016-10-03 at 13 40 39" src="https://cloud.githubusercontent.com/assets/21043023/19045451/4447a11a-896f-11e6-8d8a-84a09d84a580.png">

<img width="980" alt="screen shot 2016-10-03 at 13 40 16" src="https://cloud.githubusercontent.com/assets/21043023/19045452/444f6dbe-896f-11e6-9c49-a63fe83ea790.png">

Ponele algún margin a la descripción del evento, que la galeia quede mas linda en  la vista no pegada directo después del texto(mas margin)
 
Esta como forzado a enter los complementos

2016-10-03 16:59 UTC, felparodi commented on src/components/animals/events/MiniEvent.js
> +                          {event.description}
Contente la descripción en un div o p te va a ser mas practico para el diseño

2016-10-03 17:31 UTC, davidgivad commented on src/components/animals/events/MiniEvent.js
> +                          {event.description}
corregido

2016-10-03 19:04 UTC, bernabe9 commented
@davidgivad correcciones:
- Pedi mas animales por vez, la primera vez q entras hay mucho espacio en blanco y podria ser ocupado con mas eventos.
- Cuando cargo los eventos de un animal y luego voy a otro animal mientras esta cargando me aparecen los eventos del animal que ingrese antes(esto se soluciona haciendo que cuando desmontas el componente limpiar los eventos que tenes en el store)

2016-10-05 02:08 UTC, bernabe9 requested changes

2016-10-05 02:08 UTC, bernabe9 commented on src/actions/actionTypes.js
> +export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
tenes dos constantes que significan lo mismo, `LOAD_EVENTS_SUCCES` y `LOAD_EVENTS_SUCCESS` usa solo una

2016-10-05 02:11 UTC, davidgivad commented on src/actions/actionTypes.js
> +export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
merge error. fixed

2016-10-05 02:19 UTC, bernabe9 approved these changes

2016-10-05 02:19 UTC, merged