Se arreglo problema de raza y un detallecito de view New modal
pisgrupo9/ash_web pull request #88
Opened 2016-10-07 07:27 UTC by davidgivad

Se arreglo este card y un detalle view de New modal
https://trello.com/c/hDcLzIOx/105-que-raza-sea-obligatorio-para-caballo-perro-y-gato

2016-10-07 15:03 UTC, felparodi commented on src/containers/EditAnimalModal.js
> +    } else if ((this.props.animal.species_id == "1" || this.props.animal.species_id == "2" || this.props.animal.species_id == "5" )
david esto esta bien pero por ahora solo se sabe que perro y gato son 1 y 2, en backend no an dejado fijo el id de caballo. Asi que habra que ver como lo hacen

2016-10-07 15:04 UTC, felparodi commented on src/containers/NewAnimalModal.js
> +    if (animal.species_id == "1" || animal.species_id == "2" || animal.species_id == "5" ) {
Mismo que lo anterrior

2016-10-07 15:21 UTC, bernabe9 requested changes

2016-10-07 15:21 UTC, bernabe9 commented on src/components/animals/AnimalForm.js
> +        <div>
mal identado

2016-10-07 15:21 UTC, bernabe9 commented on src/containers/EditAnimalModal.js
> +    } else if ((this.props.animal.species_id == "1" || this.props.animal.species_id == "2" || this.props.animal.species_id == "5" )
Usa `let { species_id } = this.props.animal` para que este if te quede mucho mas corto y claro.
Usa comillas simples

2016-10-07 15:21 UTC, bernabe9 commented on src/containers/EditAnimalModal.js
> +                && this.state.animal.race == "") {
esto deberia estar en la misma linea del la condicion

2016-10-07 15:21 UTC, bernabe9 commented on src/containers/EditAnimalModal.js
> +      errors["race"] = 'Raza no puede ser vacio';
usa `dot`, `errors.race`.

2016-10-07 15:21 UTC, bernabe9 commented on src/containers/EditAnimalModal.js
> +      errors["race"] = 'Raza no puede ser vacio';
El mensaje deberia estar donde estan todos los mensajes de error

2016-10-07 15:21 UTC, bernabe9 commented on src/containers/NewAnimalModal.js
> +    if (animal.species_id == "1" || animal.species_id == "2" || animal.species_id == "5" ) {
Usa comillas simples

2016-10-07 15:21 UTC, bernabe9 commented on src/containers/NewAnimalModal.js
> +    if (animal.species_id == "1" || animal.species_id == "2" || animal.species_id == "5" ) {
Todo este if y else lo podes simplificar en dos lineas.

```
let { species_id } = animal;
requiredFields.race = species_id == '1' || species_id == '2' || species_id == '5';
```

2016-10-07 22:00 UTC, bernabe9 requested changes

2016-10-07 22:00 UTC, bernabe9 commented on src/containers/EditAnimalModal.js
> +    } else if ((species_id == '1' || species_id == '2' || species_id == '3') && (race == null || race == "")) {
Seria `((species_id == '1' || species_id == '2' || species_id == '3') && !race)`

Ademas creo que es mucha logica para una condicion if.
Considerando que lo volves a usar lo mejor seria hacer una funcion para esto

2016-10-07 22:00 UTC, bernabe9 commented on src/containers/EditAnimalModal.js
> +    const emptyChip = field === 'chip_num' && value === '';
Estas dos lineas me parecen que son tareas de un parser mas que de un metodo del componente.
Podrias hacer un parser como existe el parserAnimal que maneje esas cosas

2016-10-07 22:32 UTC, bernabe9 requested changes

2016-10-07 22:32 UTC, bernabe9 commented on src/containers/NewAnimalModal.js
> +    requiredFields.race = species_id == '1' || species_id == '2' || species_id == '3';
usa la funcion `valid.requiredRace(species_id)`

2016-10-07 23:03 UTC, bernabe9 approved these changes

2016-10-07 23:05 UTC, bernabe9 requested changes
Fix emptyChip comment

2016-10-08 00:16 UTC, bernabe9 approved these changes

2016-10-08 00:16 UTC, merged