Download Pdf y xls
pisgrupo9/ash_web pull request #94
Opened 2016-10-09 22:31 UTC by felparodi

NO ACCEPATR AUN

2016-10-09 23:16 UTC, bernabe9 requested changes

2016-10-09 23:16 UTC, bernabe9 commented on src/actions/downloadActions.js
> +      type: types.DOWNLOAD,
mal identado

2016-10-09 23:16 UTC, bernabe9 commented on src/actions/exportActions.js
> +      type: types.EXPORT_ANIMAL_PDF,
mal identado

2016-10-09 23:16 UTC, bernabe9 commented on src/actions/exportActions.js
> +      type: types.EXPORT_ANIMALS_XLS,
lo mismo

2016-10-09 23:16 UTC, bernabe9 commented on src/actions/exportActions.js
> +      let a = 'http://intgis.montevideo.gub.uy/sit/mapserv/data/Plano_Base_de_Montevideo_A1.pdf';
lo mismo

2016-10-09 23:16 UTC, bernabe9 commented on src/components/App.js
> +        <Download />
Este componente llamalo solo dentro de los componentes donde se van a descargar cosas. Evita poner componentes en el `App.js` a menos de que vayan a ser utilizados en toda la app

2016-10-09 23:31 UTC, felparodi commented on src/actions/exportActions.js
> +      let a = 'http://intgis.montevideo.gub.uy/sit/mapserv/data/Plano_Base_de_Montevideo_A1.pdf';
Esto es para probar los pdf

2016-10-09 23:31 UTC, felparodi commented on src/components/App.js
> +        <Download />
Este componte es genérico para que se puedan descargar elementos, no depende de que pagina lo usa, le da a la applicacion la posibilidad de descargar algunos archivos particular, ose en todos las paginas menos la de login y registra en el futuro?
Decís para cada una de la paginas ponerle el componte que debería estar en casi todas? 
Ademas el componte app es el que menos se re-renderiza asiéndolo mucho mas estable que este que este en este componet ya que llama un timer en el render

2016-10-09 23:40 UTC, bernabe9 commented on src/components/App.js
> +        <Download />
No serian solo dos los componentes q descargan? El listar animales y el perfil animales

2016-10-10 00:27 UTC, bernabe9 requested changes

2016-10-10 00:27 UTC, bernabe9 commented on src/components/common/Download.js
> +      setTimeout(
esta funcion la podes escribir en 3 lineas y queda mas clara

2016-10-10 00:27 UTC, bernabe9 commented on src/constants/apiMessage.js
> +export const SELECIONE_UN_ANIMAL = 'Debe selecionar un animal para poder descargar si ficha';
Seria `Debe selecionar un animal para poder descargar su ficha`

2016-10-10 00:31 UTC, bernabe9 requested changes

2016-10-10 00:31 UTC, bernabe9 commented on src/components/animals/AnimalListWrapper.js
> +
linea innecesaria

2016-10-10 00:31 UTC, bernabe9 commented on src/components/animals/AnimalListWrapper.js
> +
lo mismo

2016-10-10 00:31 UTC, bernabe9 commented on src/components/animals/AnimalListWrapper.js
> +    } else {
usa `else if` con la condicion de abajo

2016-10-10 00:31 UTC, bernabe9 commented on src/styles/styles.scss
> +    font-size: 10px;
mal ideantado de aca para abajo

2016-10-10 19:32 UTC, bernabe9 commented
Mejoras: 
- Limpiar el cache de la descarga pdf luego q salis del perfil del animal, porque sino ocurre el bug q te sigue descargando el mismo
- Preguntar al cliente q mostrar mientras se espera por el pdf

2016-10-12 20:21 UTC, bernabe9 requested changes

2016-10-12 20:21 UTC, bernabe9 commented on src/actions/exportActions.js
> +    let id = Math.floor((Math.random() * 10000) + 1);
me imagino que esto se va a volar cuando este el backend no?

2016-10-12 20:21 UTC, bernabe9 commented on src/components/reports/ReportItem.js
> +  let estado = report.url ?
usa `if`, las condiciones ternarias se usan en una linea.

2016-10-12 20:21 UTC, bernabe9 commented on src/constants/apiMessage.js
> +export const SELECIONE_UN_ANIMAL = 'Debe selecionar un animal para poder descargar su ficha';
`seleccionar`

2016-10-12 20:21 UTC, bernabe9 commented on src/constants/apiMessage.js
> +export const REPORTE_CREADO = 'Se esta generado el reporete';
`generando`

2016-10-12 20:21 UTC, bernabe9 commented on src/constants/apiMessage.js
> +export const REPORTE_TERMINDO = 'El reporte se a finalizado';
`El reporte se ha finalizado`
Aunque me parece mejor: `El reporte ya esta listo`

2016-10-12 20:21 UTC, bernabe9 commented on src/constants/apiMessage.js
> +export const REPORTE_YA_CREADO = 'El reporete ya existe, ve el menu reporets';
`El reporte ya existe en la lista de reportes`

2016-10-12 20:21 UTC, bernabe9 commented on src/constants/apiMessage.js
> +export const FICHA_CREADO = 'Se esta genreado la ficha para el animal';
`generando`

2016-10-12 20:21 UTC, bernabe9 commented on src/constants/apiMessage.js
> +export const FICHA_TERMINDO = 'Se a termindo de realizar la ficha de un animal';
`Se ha terminado de realizar la ficha de un animal`

2016-10-12 20:21 UTC, bernabe9 commented on src/containers/ReportePage.js
> +       <ReportList reports={this.props.reports} />
Mal identado

2016-10-12 20:21 UTC, bernabe9 commented on src/reducers/exportReducer.js
> +        return { urlPdf: action.urlz };
no seria `action.url` ???

2016-10-12 20:21 UTC, bernabe9 commented on src/reducers/reportReducer.js
> +      let reports =[];
espacio despues del `=`

2016-10-12 20:21 UTC, bernabe9 commented on src/styles/animal-perfil.scss
> +#app .perfil-div{
cual es la necesidad de hacer esto??

2016-10-12 20:21 UTC, bernabe9 commented on src/styles/animal-perfil.scss
> +  padding-top: 2px;
usa abreviatura de padding

2016-10-12 20:21 UTC, bernabe9 commented on src/styles/report-page.scss
> +  .report-table {
se necesita una linea vacia arriba antes de cada clase

2016-10-12 20:21 UTC, bernabe9 commented on src/styles/report-page.scss
> +    flex: 17;
usa flex completo, detallando las tres propiedades, si pones solo asi te asume que la ultima propiedad es 0 y no es compatible con safari

2016-10-12 20:21 UTC, bernabe9 commented on src/styles/report-page.scss
> +.report-titles-container-header {
pone linea vacia arriba

2016-10-12 20:21 UTC, bernabe9 commented on src/styles/report-page.scss
> +  background-color: #F7F7F7;
hace una variable para el color asi queda claro para el que lo lee

2016-10-12 20:21 UTC, bernabe9 commented on src/styles/report-page.scss
> +  flex: 5;
lo mismo que arriba, usa flex completo

2016-10-12 20:21 UTC, bernabe9 commented on src/styles/report-page.scss
> +  flex: 2;
lo mismo

2016-10-12 20:21 UTC, bernabe9 commented on src/containers/ReportePage.js
> +      <div className="report-page bg-white-color" >
evita hacer clases innecesarias como `bg-white-color` cuando directamente lo podes hacer en `report-page` cuanta menor cantidad de clases tenga mas facil es de mantener

2016-10-12 20:21 UTC, bernabe9 commented on src/styles/styles.scss
> +#app .white-color {
no usas en ningun lado esta clase, eliminala

2016-10-12 20:21 UTC, bernabe9 commented on src/styles/header.scss
> +  margin-left: 20px;
cuidado con esto! yo diria de ni modificarlo, nose cual fue la razon. Pero quedo asi el nav header:
![screenshot from 2016-10-12 17-20-21](https://cloud.githubusercontent.com/assets/18464392/19326274/35bcc746-90a0-11e6-99d5-a6a3c8ae3f48.png)

2016-10-12 20:24 UTC, felparodi commented on src/styles/header.scss
> +  margin-left: 20px;
con el nuevo item explota muchos mas el header triame la resolucion con la que te paso eso, si es con todas no lo note ayer

2016-10-13 20:23 UTC, bernabe9 requested changes

2016-10-13 20:23 UTC, bernabe9 commented on src/components/animals/AnimalListWrapper.js
> +    this.setState( { pdfAnimals: {}, xlsAnimals: '' });
Porque esto? Si ya definis el estado cuando se inicia no veo la necesidad de volver a setearlo aca

2016-10-13 20:23 UTC, bernabe9 commented on src/components/animals/AnimalListWrapper.js
> +      } else {
usa `else if`

2016-10-13 20:23 UTC, bernabe9 commented on src/components/reports/ReportList.js
> +          return (
esta linea y la de abajo escribilas en una sola linea

2016-10-13 20:23 UTC, bernabe9 commented on src/containers/AnimalPerfilPage.js
> +    this.setState({ pdfUrl: null, animalId: animalId });
porque volves a setear `pdfUrl` cuando ya se inicializa con `null`?

2016-10-13 20:23 UTC, bernabe9 commented on src/reducers/reportReducer.js
> +                       return {
esta funcion esta mal identada

2016-10-13 20:23 UTC, bernabe9 commented on src/styles/header.scss
> +@media (min-width: 768px){
Esto es lo peor que podes hacer. Si en verdad no encontraste otra solucion lo hablamos.
Creo q con la documentacion oficial de react boostrap https://react-bootstrap.github.io/components.html#navigation deberia salir

2016-10-13 20:25 UTC, felparodi commented on src/components/animals/AnimalListWrapper.js
> +    this.setState( { pdfAnimals: {}, xlsAnimals: '' });
Es lo que genrera el bug de repetir pdf

2016-10-13 20:27 UTC, felparodi commented on src/containers/AnimalPerfilPage.js
> +    this.setState({ pdfUrl: null, animalId: animalId });
Porque esta los bug de repetir pdf, ya que el contructor no se llama cada ves que se reutiliza solo la primera ves

2016-10-13 20:31 UTC, felparodi commented on src/styles/header.scss
> +@media (min-width: 768px){
Lo rompen las medias query que tiene bootrap-react, las tengo que sobrecribir para que no me afecten todo el componete ya que con los margins pira, si queres leo la doc debuelta pero no creo que me pueda aportar algo con eso.

2016-10-13 20:36 UTC, felparodi commented on src/actions/exportActions.js
> +    let id = Math.floor((Math.random() * 10000) + 1);
Si eso es asi

2016-10-14 18:26 UTC, joacolej commented on src/components/animals/AnimalListWrapper.js
> +      toastr.warning('', messages.SELECIONE_UN_ANIMAL);
falta una C en seleccione

2016-10-14 18:26 UTC, joacolej commented on src/components/animals/AnimalListWrapper.js
> +        toastr.warning('', messages.FICHA_YA_CREADO);
ficha ya creada, no creado

2016-10-14 18:26 UTC, joacolej commented on src/constants/apiMessage.js
> +export const SELECIONE_UN_ANIMAL = 'Debe seleccionar un animal para poder descargar su ficha';
Seleccione, mismo de arriba

2016-10-14 18:26 UTC, joacolej commented on src/constants/apiMessage.js
> +export const FICHA_CREADO = 'Se esta generando la ficha para el animal';
Creada, está va con tilde

2016-10-14 18:26 UTC, joacolej commented on src/constants/apiMessage.js
> +export const REPORTE_TERMINDO = 'El reporte ya esta listo';
terminado

2016-10-14 18:26 UTC, joacolej commented on src/constants/apiMessage.js
> +export const FICHA_TERMINDO = 'Se ha terminado de realizar la ficha de un animal';
terminada 

Es para discusión, per ome parece que quedaría mejor que diga "la ficha del animal" en vez de "la ficha de un animal"

2016-10-14 18:26 UTC, joacolej commented on src/constants/apiMessage.js
> +export const REPORTE_CREADO = 'Se esta generando el reporete';
está va con tilde

2016-10-14 18:26 UTC, joacolej commented on src/constants/apiMessage.js
>  export const ERROR_EMPTY_RACE = 'Raza no puede ser vacio';
esto es de un commit anterior pero vacío va con tilde

2016-10-14 18:26 UTC, joacolej commented on src/constants/apiMessage.js
> +export const FICHA_YA_CREADO = 'Ya existe la ficha para este animal, vea la seccion de reportes';
creada, sección va con tilde

2016-10-15 00:28 UTC, bernabe9 requested changes

2016-10-15 00:28 UTC, bernabe9 commented on src/containers/AddEventModal.js
> +  animalActions: object.isRequired,
coma al final innecesaria

2016-10-15 00:28 UTC, bernabe9 commented on src/containers/ReportePage.js
> +  reports: array.isRequired,
coma al final innecesaria

2016-10-15 00:28 UTC, bernabe9 commented on src/reducers/exportReducer.js
> +      case types.EXPORT_ANIMAL_PDF: {
de aca para abajo mal identado

2016-10-15 17:09 UTC, bernabe9 approved these changes

2016-10-15 17:10 UTC, merged