add edit image perfil button & fixed Bug
pisgrupo9/ash_web pull request #95
Opened 2016-10-10 15:14 UTC by davidgivad

Se arreglo bugs:
https://trello.com/c/OP6tStUA/109-bug-listar-eventos-cuando-la-descripcion-es-muy-grande-se-sale-del-contendor
https://trello.com/c/463z5m0s/99-mostrar-foto-de-perfil-actual-cuando-edito-la-informacion-del-animal

2016-10-10 17:59 UTC, bernabe9 requested changes

2016-10-10 17:59 UTC, bernabe9 commented on src/styles/animal-perfil.scss
> +  overflow: scroll;
no uses scroll

2016-10-10 18:38 UTC, davidgivad commented on src/styles/animal-perfil.scss
> +  overflow: scroll;
Si la descripcion es muy larga de toda manera vas tener que "scrollear", porque en una pantalla no te va entrar todo el contenido de eventos. Es preferible que haya un scroll para controlar el esqueleto del diseño. Igual hoy pregunto al cliente. Pongo una imagen como se veria sin scroll.
![screenshot from 2016-10-10 15-27-07](https://cloud.githubusercontent.com/assets/21270775/19247020/8953017e-8eff-11e6-9f8a-3c60f62b240c.png)

2016-10-13 20:35 UTC, bernabe9 requested changes

2016-10-13 20:35 UTC, bernabe9 commented on src/styles/animal-perfil.scss
> +  color: #9B9B9B;
para los colores usa variables asi se pueden distinguir

2016-10-13 20:35 UTC, bernabe9 commented on src/styles/styles.scss
> +  bottom: -13px;
no uses numeros negativos

2016-10-13 20:35 UTC, bernabe9 commented on src/styles/styles.scss
> +  bottom: -60px;
bottom ya esta definido y no uses numeros negativos

2016-10-13 20:35 UTC, bernabe9 commented on src/styles/styles.scss
> +  right: -7px;
no uses numeros negativos

2016-10-13 20:35 UTC, bernabe9 commented on src/styles/styles.scss
> +  box-shadow: 1px 1px 1px #888888;
usa variables para los colores

2016-10-13 20:35 UTC, bernabe9 commented on src/styles/styles.scss
> +  padding-top: 2px;
abrevia padding

2016-10-14 18:16 UTC, joacolej commented on src/styles/animal-perfil.scss
> +  overflow: scroll;
yo creo que prefiero con scroll

2016-10-15 17:15 UTC, bernabe9 commented
Asegurate que no pase esto:
![screenshot from 2016-10-15 14-13-59](https://cloud.githubusercontent.com/assets/18464392/19411968/b7c06142-92e1-11e6-8e9e-e36b55e143c2.png)

2016-10-15 22:46 UTC, davidgivad commented on src/styles/styles.scss
> +  right: -7px;
lo uso para posicionar bien el botoncito fijate que position esta en relative.

2016-10-18 22:49 UTC, davidgivad commented
aaa

2016-10-18 23:15 UTC, bernabe9 requested changes

2016-10-18 23:15 UTC, bernabe9 commented on src/styles/animal-perfil.scss
> +  overflow: scroll;
ponele `auto` porque sino cuando la descripcion es corta igual se muestra el scroll

2016-10-18 23:25 UTC, bernabe9 commented
Las palabras se cortan hacia abajo y ni aparece un guion como si continuara la palabra:

La palabra "probando" deberia estar toda junta o quebrada por un guion
![screenshot from 2016-10-18 20-24-13](https://cloud.githubusercontent.com/assets/18464392/19500132/e18bdb6e-9570-11e6-90f6-f4fced023c3d.png)

2016-10-18 23:27 UTC, bernabe9 requested changes

2016-10-18 23:27 UTC, bernabe9 commented on src/styles/animal-perfil.scss
> +  word-break: break-all;
Yo sacaria esta propiedad. Nadie va a escribir una palabra mas larga que el contendor. Mira la captura que te puse

2016-10-18 23:40 UTC, bernabe9 commented
Revisa que los animales 70 y 73 se vean bien

2016-10-19 04:47 UTC, davidgivad commented on src/styles/animal-perfil.scss
> +  word-break: break-all;
oka. Pero voy a sacar +  overflow-x: hidden; por si alguien escribe las palabras sin espacio

2016-10-20 20:16 UTC, bernabe9 requested changes

2016-10-20 20:16 UTC, bernabe9 commented on src/styles/events.scss
> +  flex: 1;
flex completo

2016-10-20 20:16 UTC, bernabe9 commented on src/styles/mini-view.scss
> +  margin-top: 25px;
porque cambiaste esto?

2016-10-20 20:16 UTC, bernabe9 commented on src/styles/styles.scss
> +.btn-circle-edit {
comparte muchisimas propiedades con `.btn-circle` usa `@extend`

2016-10-20 20:16 UTC, bernabe9 commented
El animal 73 se sigue viendo mal en resoluciones de 1000px y mobile:

![screenshot from 2016-10-20 17-04-04](https://cloud.githubusercontent.com/assets/18464392/19576328/f9f33b7e-96e8-11e6-84ee-e5e9bc03eea4.png)
![screenshot from 2016-10-20 17-05-29](https://cloud.githubusercontent.com/assets/18464392/19576330/fb153700-96e8-11e6-8059-6fa51097de5e.png)

2016-10-20 20:23 UTC, davidgivad commented on src/styles/mini-view.scss
> +  margin-top: 25px;
eso es de mini-view que lo corregi que yo lo habia tocado sin querer

2016-10-21 00:30 UTC, bernabe9 commented
Nose que propiedad cambiaste, pero el boton se sale del contenedor:
![screenshot from 2016-10-20 21-29-44](https://cloud.githubusercontent.com/assets/18464392/19582601/66fcdfc2-970c-11e6-9d80-48fb7296894f.png)

2016-10-21 01:05 UTC, bernabe9 approved these changes

2016-10-21 01:06 UTC, merged