Si no hay fotos en la galería se despliega un mensaje
pisgrupo9/ash_web pull request #97
Opened 2016-10-11 02:40 UTC by Isa14

2016-10-11 02:52 UTC, felparodi commented on src/components/animals/ImagesGallery.js
> +      } else if (imageList.length > 0) {
Innecesario uno de los if ya que length para una lista es mayo o igual a cero siempre

2016-10-12 01:04 UTC, bernabe9 requested changes

2016-10-12 01:04 UTC, bernabe9 commented on src/components/animals/ImagesGallery.js
> +      if (imageList.length == 0) {
es suficiente con `!imageList.length`

2016-10-12 01:04 UTC, bernabe9 commented on src/styles/img-galeria.scss
> +.empty-gallery-container p {
No uses tags html para los css, usa solo clases. Aca estas usando el tag `p`.
Aplica una clase directamente sobre el tag html que queres dar estilo

2016-10-12 23:33 UTC, bernabe9 approved these changes

2016-10-12 23:33 UTC, merged